### ISSUE TITLE
Allow working directory to specified when running executables

### ISSUE THREAD

**Issue by jla2000** [Civitasv/cmake-tools.nvim#100]
**Describe the problem or limitation you are having**
I need to set the working directory of some cmake targets to something else. I'm not sure on how to do this right now as it will always choose the build folder where the executable is run with CMakeRun as the working directory.

**Describe the solution you'd like**
Something similiar to CMakeLaunchArgs, like CMakeLaunchDir where an absolute or relative (eg ../) path to the build folder can specified for both simply running the executable or debugging with nvim-dap.

**Describe alternatives you've considered**
Right now I have no real alternative but to manually run with the adopted working dir, but eg for debugging it would be really nice to have it just working out of the box.

**Additional context**
--

**Comment by jla2000** [comment]
> You can change current working dir by change “vim.loop.cwd()”.

Just override this function and return a string pointing to the working directory?

**Comment by Civitasv** [comment]
An example: https://vi.stackexchange.com/questions/34871/set-current-working-directory-when-opening-vim.

**Comment by hfn92** [comment]
Doesn't `cmake-tool` always `cd` into the directory of the executable before running? I think OP is asking about allowing somethin like
`cd /custom/dir && path/to/exe/exe`
instead of
`cd path/to/exe/ && exe`

**Comment by Civitasv** [comment]
@hfn92 You are right, I misunderstood.

**Comment by jla2000** [comment]
@hfn92 Yes, this is what I meant. I would like to be able to launch the executable with another cwd, not directly the path where the executable is stored. It would be nice if this could be also like a relative path so you could pass ../ for example to reference the parent folder of the binary

**Comment by jla2000** [comment]
So what would could work is cd /path/to/exe && cd custom/dir && path/to/exe/exe

Then it would be possible to specify a relative or absolute path with custom/dir

**Comment by hfn92** [comment]
I wonder if a nice way to configure this would be using the same way I intend to with with this feature https://github.com/Civitasv/cmake-tools.nvim/issues/90
This could also be used to configure launch arguments
```lua
return {
  working_drectory = "../",
  args = [[arg1 arg2]],
  inherit_build_environment = true,
  env { 
    log_file = "/tmp/log.txt",
    log_level = "trace",
  }
}
```

I think this would be a really convenient way to configure these things, since it works directly in a vim buffer and is easy to persist

**Comment by Civitasv** [comment]
> I think this would be a really convenient way to configure these things, since it works directly in a vim buffer and is easy to persist

That’s indeed a convenient way!

**Comment by jla2000** [comment]
yeah this looks like a good idea! 😃 Is this then configured on a global level or per target basis?

**Comment by hfn92** [comment]
> yeah this looks like a good idea! smiley Is this then configured on a global level or per target basis?


This is for a specific target. But there is also a global config. So this could be possible
```lua
return {
  inherit_working_dir = true -- inherit from global config
  -- working_drectory = "../",
  args = [[arg1 arg2]],
  inherit_build_environment = true,
  env { 
    log_file = "/tmp/log.txt",
    log_level = "trace",
  }
}
```

**Comment by jla2000** [comment]
Really cool! :D Thank you very much!

**Comment by hfn92** [comment]
> So what would could work is `cd /path/to/exe && cd custom/dir && path/to/exe/exe`
> 
> Then it would be possible to specify a relative or absolute path with `custom/dir`

I guess usually you'd have some variable to use as a base like `${build_dir}/../`, `${source_dir}/../build/`.
I've thinking on how to integrate that without having to write a string parser.
I guess we could take advantage of the fact we're using lua as config files and inject some variables when opening the popup window:
```lua

local vars = {
  build_dir = "/home/src/build_debug/"
  source_dir = "/home/src/"
  target_dir = "/home/src/build_debug/bin/"
}

return {
  working_drectory =  vars.source_dir .. "../../",
  inherit_build_environment = true,
  env { 
    log_file = "/tmp/log.txt",
    log_level = "trace",
  }
}
````

When closing the config this would evaluate directly. Meaning it's not dynamic. So when opening the config the next time it would show

```lua
local vars = {
  build_dir = "/home/src/build_debug/"
  source_dir = "/home/src/"
  target_dir = "/home/src/build_debug/bin/"
}

return {
  working_drectory =  "/home/src/../../",
  inherit_build_environment = true,
  env { 
    log_file = "/tmp/log.txt",
    log_level = "trace",
  }
}
```
But since the directories should be static this should be fine imo

**Comment by jla2000** [comment]
I think this would be even better, its probably a common case that someone wants a path relative to either source or build directory.

```lua
local vars = {
  build_dir = "/home/src/build_debug/"
  source_dir = "/home/src/"
  target_dir = "/home/src/build_debug/bin/"
}
```

For the variables part, would it be possible to derive them somehow  from available info? For example the build folder for every target right now is known and should be used as input in this configs. Do you think there is a way doing this without a parser?

**Comment by hfn92** [comment]
If I understand you correctly, yes thats the idea. `vars` could be dynamically injected into the config depending on the targets.

So `CMakeTargetsSttings Project` might show
```lua
local vars = {
  target_dir = "/home/src/build_debug/Project/bin/"
}
```
while `CMakeTargetSettings Tests` might show
```lua
local vars = {
  target_dir = "/home/src/build_debug/Tests/bin/"
}
```
depending on your cmake config. The problem is. if you change the binary dir of your target `working_directoy` would not be updated since the settings are already evaluated. Only `vars.target_dir` would show the new directory.

Maybe we can make it dynamic using `function()` but I"m not sure.

**Comment by jla2000** [comment]
But vars would then be manually set on project level right?

Because cmake targets can have different build folders, so it would be nice to specify a pattern for a target working directory or at least remove the need to specify always that build folder.

In my case, I have a lot of cmake targets that have each a different build folder, so ideally i would maybe configure on target or project level something like `vars.buildFolder .. "/../"`. But if every time the `vars.buildFolder` would need to be manually defined that would be lots of work (100+ targets). Right now it is somehow derived and cd'ed into when running a target. Can it not somehow be injected or made available to the configs?

**Comment by hfn92** [comment]
> But vars would then be manually set on project level right?

They would be predefined by `cmake-tools`. Some vars would change depending on the target. 

> Because cmake targets can have different build folders, so it would be nice to specify a pattern for a target working directory or at least remove the need to specify always that build folder.
> 
> In my case, I have a lot of cmake targets that have each a different build folder, so ideally i would maybe configure on target or project level something like `vars.buildFolder .. "/../"`. But if every time the `vars.buildFolder` would need to be manually defined that would be lots of work (100+ targets). Right now it is somehow derived and cd'ed into when running a target. Can it not somehow be injected or made available to the configs?

I'm not sure I understand Do you want something like.
```lua
{
  working_directory = "${build_dir}../../',
}
```
In the base settings that gets applied to every target?

**Comment by jla2000** [comment]
Ahh okay, so the set of vars will be automatically defined by cmake-tools and is available in the config prompt. I think this is fine then. (I thought the vars set needed to be defined by the user). 

> {
>   working_directory = "${build_dir}../../',
> }
> In the base settings that gets applied to every target?

As for this part, I don't think it would be absolutely necessary, at least for my usecase. But I think in general it would be nice of course if a user could define a pattern like this and have it override the default for the targets.

**Comment by jla2000** [comment]
At least it would reduce the number of configuration needed to get different targets working that  expect similar settings

**Comment by hfn92** [comment]
@jla2000 @Civitasv  I have something working here https://github.com/hfn92/cmake-tools.nvim/tree/cwd

It works and think it's a powerful solution. But it might not be that intuitive. Please tell me what to think.

If you want to change the working directory of all targets you can use `CMakeSettings` and edit `working_directory`
This is the default for the base settings:
```lua
local vars = {
  dir = {
    binary = "${dir.binary}",
    build = "../build_Debug/"
  }
}
return {
  env = {},
  working_dir = "${dir.binary}"
}
```

If you want to change working dir for a single target, use `CMakeTargetSettings`. You need to **add** `working_dir` because it can't exist per default.
```lua
local vars = {
  dir = {
    binary = "/home/fab/Desktop/cmake-gtest.nvim/test/../build_Debug//",
    build = "../build_Debug/"
  }
}
return {
  args = {},
  env = {},
  inherit_base_environment = true,
  -- add working dir here
}

```

You can use `${}` syntax to dynamically resolve one of the available variable on execution. Or statically resolve it.
E.g `working_dir = var.dir.binary` will be resolved to `working_dir = "/home/fab/Desktop/cmake-gtest.nvim/test/../build_Debug//"`

**Comment by Civitasv** [comment]
I think it indeed is a very clean solution

**Comment by hfn92** [comment]
> I think it indeed is a very clean solution
Since you like it I opened a pr :)

**Comment by hfn92** [comment]
> > I think it indeed is a very clean solution

Since you like it I opened a pr :)

**Comment by jla2000** [comment]
@hfn92
This looks really good! :)

I'm getting an error tho after running :CMakeGenerate and then :CMakeRun for the first time in a simple project:
```
Error executing vim.schedule lua callback: ...hare/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:482: attempt to index field 'base_settings' (a nil value)
stack traceback:
        ...hare/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:482: in function 'get_launch_path'
        ...hare/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:572: in function 'callback'
        ...hare/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:363: in function 'on_success'
        .../nvim/lazy/cmake-tools.nvim/lua/cmake-tools/quickfix.lua:118: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
Press ENTER or type command to continue
```

After running :CMakeSettings and :CMakeTargetSettings and saving the buffers it did work, maybe there is nothing generated as default for the target? Or did I miss something..

**Comment by hfn92** [comment]
> After running :CMakeSettings and :CMakeTargetSettings and saving the buffers it did work, maybe there is nothing generated as default for the target? Or did I miss something..
Probably a bug .. I'll look into it

**Comment by hfn92** [comment]
> @hfn92 This looks really good! :)
> 
> I'm getting an error tho after running :CMakeGenerate and then :CMakeRun for the first time in a simple project:
> 
> ```
> Error executing vim.schedule lua callback: ...hare/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:482: attempt to index field 'base_settings' (a nil value)
> stack traceback:
>         ...hare/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:482: in function 'get_launch_path'
>         ...hare/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:572: in function 'callback'
>         ...hare/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:363: in function 'on_success'
>         .../nvim/lazy/cmake-tools.nvim/lua/cmake-tools/quickfix.lua:118: in function ''
>         vim/_editor.lua: in function <vim/_editor.lua:0>
> Press ENTER or type command to continue
> ```
> 
> After running :CMakeSettings and :CMakeTargetSettings and saving the buffers it did work, maybe there is nothing generated as default for the target? Or did I miss something..

This should fix it https://github.com/Civitasv/cmake-tools.nvim/pull/119

Thanks for trying out :)

**Comment by jla2000** [comment]
> This should fix it #119
Yes, it worked now :)

> Thanks for trying out :)
Thank you for implementing this 🥇

**Comment by hfn92** [comment]
> > This should fix it #119
> 
> Yes, it worked now :)
> 
> > Thanks for trying out :)
> 
> Thank you for implementing this 1st_place_medal

You're welcome :)

**Comment by Civitasv** [comment]
#117 Should add the ability to specify working directory for targets, could we close this issue?

**Comment by jla2000** [comment]
Okay sure, I'll close it
