### ISSUE TITLE
Telescope cmake_tools throws

### ISSUE THREAD

**Issue by Amleto** [Civitasv/cmake-tools.nvim#109]
**Bug description**

I'm not sure if there are some undocumented pre-reqs or anything?

Run `:Telescope cmake_tools` gives:
```
Error executing Lua callback: ...ta/lazy/cmake-tools.nvim/lua/cmake-tools/file_picker.lua:18: bad argument #1 to 'ipairs
' (table expected, got nil)
stack traceback:
        [C]: in function 'ipairs'
        ...ta/lazy/cmake-tools.nvim/lua/cmake-tools/file_picker.lua:18: in function 'get_files_from_target'
        ...ta/lazy/cmake-tools.nvim/lua/cmake-tools/file_picker.lua:51: in function 'get_source_files'
        ...ake-tools.nvim/lua/telescope/_extensions/cmake_tools.lua:30: in function 'fn'
        ...ake-tools.nvim/lua/telescope/_extensions/cmake_tools.lua:16: in function <...ake-tools.nvim/lua/telescope/_ex
tensions/cmake_tools.lua:8>
        .../nvim-data/lazy/telescope.nvim/lua/telescope/command.lua:193: in function 'run_command'
        .../nvim-data/lazy/telescope.nvim/lua/telescope/command.lua:253: in function 'load_command'
        ...Local/nvim-data/lazy/telescope.nvim/plugin/telescope.lua:108: in function <...Local/nvim-data/lazy/telescope.
nvim/plugin/telescope.lua:107>
```

**Steps to reproduce**
I have telescope and cmake_tools plugins loaded. My current dir is a small c++/cmake repo. I run.
`:Telescope cmake_tools`

<details><summary>Minimal configuration</summary>
</details>

**Expected behavior**
The telescope command executed ok. 

**Screenshots**

**Environment**

- OS: Win10
- Plugins commit hash:  8e8e9520bf09c52f540b8c12ae29

**Comment by Civitasv** [comment]
@hfn92 can you see it

**Comment by hfn92** [comment]
can you upload the contens of `./cmake/api` ? the whole project would be even better of course

**Comment by hfn92** [comment]
Still I think this should fix it https://github.com/Civitasv/cmake-tools.nvim/pull/110
But would be good to know how the cmake api response looks

**Comment by Amleto** [comment]
> can you upload the contens of `./cmake/api` ? the whole project would be even better of course

I'm sorry, I don't know what that refers to.

[CMakeLists.txt](https://github.com/Civitasv/cmake-tools.nvim/files/12207618/CMakeLists.txt)
main.cpp:
```cpp
#include <algorithm>
#include <iostream>
#include <list>
#include <string>
#include <vcruntime.h>
#include <vector>

#include "other_type.h"

//  help string
auto foo(int a, char y, size_t sz) -> std::list<int> {
    std::list<int> xxx;
    xxx.clear();
    return xxx;
}

int main() {

    std::cout << "hello\n";

    tempT<int> tt;
    tt.y = 1;

    auto l = foo(0, 'y', 9);
    auto l1 = foo;

    std::vector<int> is{1,2,3};
    is.pop_back();


    //std::transform()

    std::cin.get();

  return 0;

}

```

other_type.h:
```cpp
#pragma once

class other_type {
public:
    int get_int() { return 2; }    
            
};

template<typename T>
class tempT {
    public:
        T t;
};

```

**Comment by Amleto** [comment]
ah, ok. I have seen the dir.

[Here](https://gist.github.com/Amleto/a9279525c3ff8b82d3dcf2a8c942ce02) is a gist of the reply.

There are two zero-byte files in the query dir.

![image](https://github.com/Civitasv/cmake-tools.nvim/assets/2996796/ab9c798d-ae61-4466-84e8-b395b45360c9)

**Comment by hfn92** [comment]
Ah, I see some of the visual studio specific targets were causing issues. Thanks

Btw does the fix work?

**Comment by Amleto** [comment]
Yes, works great. Thanks for the extension!
