### ISSUE TITLE
After set env variables, can't find CMAKE_ROOT

### ISSUE THREAD

**Issue by lbiaggi** [Civitasv/cmake-tools.nvim#11]
Hi,

Your commit 14603f0  broke the plugin, I can't use `CMakeBuild`, `CMakeGenerate` didn't test other commands, but I think they are on the same boat.

```
Error executing Lua callback: .../.nvim/plugged/cmake-tools.nvim/lua/cmake-tools/init.lua:99: attempt to index upvalue 'config' (a nil value)
stack traceback:
        .../.nvim/plugged/cmake-tools.nvim/lua/cmake-tools/init.lua:99: in function <.../.nvim/plugged/cmake-tools.nvim/lua/cmake-tools/init.lua:87>
```

Anyway, I really like your work, this excellent plugin :D

Regards,
Lucas

**Comment by Civitasv** [comment]
Hi, Lucas, do you use `require("cmake-tools'').setup()`

**Comment by Civitasv** [comment]
Please try the latest commit. I've gave config a default value now, it should work. But normally you should call `setup` in your nvim config.

**Comment by lbiaggi** [comment]
Hey, yeah, I did that, it worked flawlessly until recently

Well, Now I'm receiving this error about it can't find CMAKE_ROOT, but if I run from terminal `cmake -H. -S. -Bbuild [options]` works as expected.

**Comment by Civitasv** [comment]
That's weird, I'll check soon.

**Comment by lbiaggi** [comment]
I will poke around if I can provide more useful information

**Comment by lbiaggi** [comment]
I think, I found the issue
https://github.com/Civitasv/cmake-tools.nvim/blob/master/lua/cmake-tools/utils.lua#L102 if env is nil it cleans `CMAKE_ROOT`

**Comment by Civitasv** [comment]
Didn't expect that. If `cmake-kits.json` is not provided, `env` should be {}. I thought the env passed to `Job:new` will append to existing env variables.

**Comment by lbiaggi** [comment]
Yeah, me too, I went to recheck about that in their documentation, but didn't find anything telling the opposite too, don't know, maybe related to the libuv environment?

**Comment by Civitasv** [comment]
Well, I couldn't find any useful information about env config of `Job:new`. Maybe I should set env variables in another way.

**Comment by lbiaggi** [comment]
Just to let you know, I decide to poke around the issues there, found a much better solution based on this https://github.com/nvim-lua/plenary.nvim/issues/182

if I define `cmake_command` with something like `/usr/bin/cmake` it works as expected

**Comment by lbiaggi** [comment]
My bad, I closed it before suggesting anything.

Maybe we could generate the const.cmake_command using the output of `which cmake` or something similar. Although, just updating the docs to inform about it defining it.

**Comment by Civitasv** [comment]
Thanks for your useful information.
Maybe I should update env like `{ path = vim.env["PATH"], NO_COLOR = 1 }` according to https://github.com/nvim-lua/plenary.nvim/issues/182#issuecomment-876739738.

**Comment by Civitasv** [comment]
> Maybe we could generate the const.cmake_command using the output of `which cmake` or something similar.

Yep, that can be a way to solve this problem.

**Comment by Civitasv** [comment]
> > Maybe we could generate the const.cmake_command using the output of `which cmake` or something similar.
> 
> Yep, that can be a way to solve this problem.

But if I think it's not okay to lose all other environment variables if I add one variable.

**Comment by lbiaggi** [comment]
I will test your suggestion

**Comment by lbiaggi** [comment]
It worked (as expected), but I think it is less burdensome that way than trying to guess the correct cmake.
I “implemented” it like this.
```
    utils.job = Job:new({
        command = cmd,
        args = args,
        env = vim.tbl_extend("force", env, { path = vim.fn.getenv("PATH") }),
        cwd = opts.cwd,
        on_stdout = vim.schedule_wrap(append_to_cmake_console),
        on_stderr = vim.schedule_wrap(append_to_cmake_console),
        on_exit = vim.schedule_wrap(function(_, code, signal)
            append_to_cmake_console("Exited with code " .. (signal == 0 and code or 128 + signal))
            if code == 0 and signal == 0 then
                if opts.on_success then
                    opts.on_success()
                end
            elseif opts.cmake_show_console == "only_on_error" then
                utils.show_cmake_console(opts.cmake_console_size)
                vim.api.nvim_command("cbottom")
            end
        end),
    })
```

**Comment by lbiaggi** [comment]
Meh, it worked on my machine :cry: 

I'm using the nightly version, maybe we should enforce the oppositive? I mean env populating a table/array with path

**Comment by Civitasv** [comment]
I don't understand, can you explain more? or make a pull request? Thanks in advance.

**Comment by Civitasv** [comment]
> other option is just to update the docs to inform about it defining it.

I start thinking if this is better. 😢

**Comment by Civitasv** [comment]
No, I’m using 0.8.0

**Comment by Civitasv** [comment]
I find that cmake can set environmental variables using -E option, I’ll check if it works.

**Comment by Civitasv** [comment]
> I find that cmake can set environmental variables using -E option, I’ll check if it works.

Yeah, this finally works. 

https://github.com/Civitasv/cmake-tools.nvim/blob/1ca5c35b340f735f299e64c2c850a08057ecfbb9/lua/cmake-tools/utils.lua#L101

**Comment by lbiaggi** [comment]
🤩 I will test it when i get in the office

**Comment by lbiaggi** [comment]
If I disable presets, it works, but I will comment about it on #7

**Comment by lbiaggi** [comment]
I'm closing this one. Since you already found a suitable solution.
