### ISSUE TITLE
  build_options are saved in session

### ISSUE THREAD

**Issue by hfn92** [Civitasv/cmake-tools.nvim#112]
I noticed that  `build_options`  are saved in the session config

```lua
...
  build_options = { "-j32" },
...
```
I looks like they take precedence over the config passed to `setup`. E.g once saved the user has no way to change those.

Should `build_options` be removed from session? 
Alternatively should they be configurable via the config window? That would mean the config passed to `setup` is then just the default.

**Comment by Civitasv** [comment]
> Should build_options be removed from session?

It should be removed, we should just save the options which are generated by our plugin.

> Alternatively should they be configurable via the config window? 

I think that’s nice, or even we can use the config window to config everything that we can use command previously, it seems unified.

**Comment by Civitasv** [comment]
I've pushed a fix: #8e3d276757e6ce22b06c03f5073db9acf7c2eaef.

**Comment by Civitasv** [comment]
> Alternatively should they be configurable via the config window? That would mean the config passed to `setup` is then just the default.

We can add `generate_options` and `build_option` to the `CMakeSettings` config window imo.

**Comment by hfn92** [comment]
> > Alternatively should they be configurable via the config window? That would mean the config passed to `setup` is then just the default.
> 
> We can add `generate_options` and `build_option` to the `CMakeSettings` config window imo.

Yeah I thinks thats good.

**Comment by Civitasv** [comment]
I've moved `generate_options` and `build_options` to `CMakeSettings`.
