### ISSUE TITLE
Does CMakeSettings support args or not?

### ISSUE THREAD

**Issue by Civitasv** [Civitasv/cmake-tools.nvim#115]
From the docs:
https://github.com/Civitasv/cmake-tools.nvim/blob/0723195319e39fe4833f29fe02ae004e9d7b7402/docs/settings.md?plain=1#L66-L77

CMakeSettings does not support args option.

But from init.lua:

https://github.com/Civitasv/cmake-tools.nvim/blob/0723195319e39fe4833f29fe02ae004e9d7b7402/lua/cmake-tools/init.lua#L24-L27

It has an args field.

Is this intentional for future implementation? @hfn92

**Comment by hfn92** [comment]
sorry my mistake. line 25 should be removed

**Comment by Civitasv** [comment]
Okay, I will remove it.
