### ISSUE TITLE
Error after :CMakeGenerate and any further attempt load cmake-tools

### ISSUE THREAD

**Issue by jla2000** [Civitasv/cmake-tools.nvim#122]
**Bug description**

After running first :CMakeGenerate
```
E219: Missing {.
Error executing vim.schedule lua callback: ...hare/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:1376: Failed to set autocmd
stack traceback:
        [C]: in function 'nvim_create_autocmd'
        ...hare/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:1376: in function 'create_regenerate_on_save_autocmd'
        ...hare/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:157: in function 'on_success'
        .../nvim/lazy/cmake-tools.nvim/lua/cmake-tools/quickfix.lua:118: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

Quitting, and returning to CMakeLists.txt with Ctrl+o
```
Error detected while processing BufReadPost Autocommands for "*":
Error executing lua callback: /usr/share/nvim/runtime/filetype.lua:21: Error executing lua: /usr/share/nvim/runtime/filetype.lua:22: BufReadPost Autocommands for "*"..FileType Autocommands for "cmake": Vim(append):E219: Missing {.
stack traceback:
        [C]: in function 'nvim_cmd'
        /usr/share/nvim/runtime/filetype.lua:22: in function </usr/share/nvim/runtime/filetype.lua:21>
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:21: in function </usr/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:21: in function </usr/share/nvim/runtime/filetype.lua:10>
```

and after:

```
Failed to run `config` for cmake-tools.nvim

...hare/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:1376: Failed to set autocmd

# stacktrace:
  - /cmake-tools.nvim/lua/cmake-tools/init.lua:1376 _in_ **create_regenerate_on_save_autocmd**
  - /cmake-tools.nvim/lua/cmake-tools/init.lua:68 _in_ **setup**
  - /usr/share/nvim/runtime/filetype.lua:22
  - /usr/share/nvim/runtime/filetype.lua:21
```

**Comment by jla2000** [comment]
@hfn92 I think it might be that these bugs were introduced with this recent addition of the :CMakeSettings feature

**Comment by Civitasv** [comment]
> E219: Missing {.

Why this happens?

**Comment by jla2000** [comment]
I'm not sure, it always disaplays that afer :CMakeGenerate.
I dont know how to investigate it further as for example switching to another project does not work as well :/

Eg when I quit neovim and open in in another project eg 'test-project', i get this error:
```
|| CMake Error: Unable to (re)create the private pkgRedirects directory:
|| /code/other-project/build/CMakeFiles/pkgRedirects
|| Exited with code 1
```

Somehow it tries to do something with 'other-project' although im in 'test-project' and they should not be related

**Comment by jla2000** [comment]
Sure thing, this is the content:
```lua
return {
  build_directory = "build/ninja_clang11_linux_x86_64_configX",
  build_type = "Debug",
  configure_preset = "ninja_clang11_linux_x86_64_configX",
  query_directory = "build/ninja_clang11_linux_x86_64_configX/.cmake/api/v1/query",
  reply_directory = "build/ninja_clang11_linux_x86_64_configX/.cmake/api/v1/reply",
  target_settings = {}
}
```

**Comment by Civitasv** [comment]
Maybe try using the latest commit. See if errors disappear.

**Comment by hfn92** [comment]
If that doesn't help try closing all nvim instances and deleting the session file

**Comment by jla2000** [comment]
I tried both, but without success. The errors still persist.

**Comment by Civitasv** [comment]
Can you try setting `cmake_regenerate_on_save` to false?

**Comment by hfn92** [comment]
Can you take a look at (or post) the output from
`lua vim.notify(vim.inspect(require("cmake-tools.file_picker").get_cmake_files()))`
maybe there are some suspicious file paths

**Comment by jla2000** [comment]
@Civitasv 
Setting `cmake_regenerate_on_save ` to false does prevent these kind of error messages from appearing.

@hfn92 
I just checked it, its a huge list of files (cant post because its some project from work), but the files here look reasonable to me (looks like just a list of all files used by cmake)

**Comment by jla2000** [comment]
But I guess there is some problem with the autocommands that try to regenerate the cmake

**Comment by jla2000** [comment]
But switching to another project and generating does not work I think this might be an unrelated other issue

**Comment by Civitasv** [comment]
I think it is enough to close neovim and remove session files.

**Comment by jla2000** [comment]
I checked now all the file paths from the previously posted command, there were only listed files contained in the project such as many CMakeFiles.txt, and xyz.cmake

**Comment by jla2000** [comment]
I was not able to find there anything else suspicous

**Comment by jla2000** [comment]
Hmmm I think I found something...

Some files are listed here like this:
```
 "src-gen/test-service}/xyz.cmake", 
```

The folder here seems to contain `}` in its name.

**Comment by Civitasv** [comment]
> "src-gen/test-service *}* /xyz.cmake", 

That's it. This `}` leads to `E219: Missing {.`

I wonder if this path is right?

**Comment by jla2000** [comment]
Yes the path is right 0_o

**Comment by jla2000** [comment]
So probably an error then when parsing this list

**Comment by Civitasv** [comment]
Yes, I will see what I can do.

**Comment by Civitasv** [comment]
The latest commit should fix this problem. @jla2000

**Comment by jla2000** [comment]
Yes that fixed it :)
Thank you very much @Civitasv 

As for the other issue I mentioned with switching projects, I'll create another Issue and close this one
