### ISSUE TITLE
cmake-tools decrease Neovim startup speed when start Neovim in `$HOME` folder on macOS

### ISSUE THREAD

**Issue by Mayrixon** [Civitasv/cmake-tools.nvim#123]
**Bug description**

When start Neovim in `$HOME` folder or open a file in `$HOME` folder with this plugin after the commit `69add83`, the plugin will consume around 63 seconds measured with `nvim --startuptime` tested on a M1 Pro MacBook Pro.

**Steps to reproduce**

<details><summary>Minimal configuration</summary>
<pre>
-- ~/workspace/repro.lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable",
		lazypath,
	})
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

require("lazy").setup({
	spec = {
		{
			"Civitasv/cmake-tools.nvim",
			dependencies = { "nvim-lua/plenary.nvim", "nvim-telescope/telescope.nvim" },
			-- commit = "69add83",
			opts = {},
		},
	},
})
</pre>
</details>

Shell commands to reproduce:

```bash
cd ~
nvim -u ~/workspace/repro.lua
```

**Expected behavior**

The Neovim startup time should not be affected significantly.

**Screenshots**

**Environment**

- OS: macOS 14 Sonoma Public Beta 2
- Desktop environment: 
- Plugins commit hash: 029978778651e52f4fac8894f3c74067fa4a2758

**Additional context**
<!-- Add any other context about the problem here. --

**Comment by Civitasv** [comment]
Before commit 69add83, does it work fine?

**Comment by Mayrixon** [comment]
I tested 69add837ebcf1b0f8fe539e8386a2ceaeb58983e and 0723195319e39fe4833f29fe02ae004e9d7b7402, which is the previous commit of 69add837ebcf1b0f8fe539e8386a2ceaeb58983e. Both commits work well for me.

**Comment by Mayrixon** [comment]
No. I checked with `fd CMakeLists.txt`. The most shallow one is located in folder `~/workspace/someproject/CMakeLists.txt`.

**Comment by Civitasv** [comment]
Try the latest commit.

**Comment by Mayrixon** [comment]
It fixed the problem. Thanks for the quick response!
