### ISSUE TITLE
Unable to switch between projects properly

### ISSUE THREAD

**Issue by jla2000** [Civitasv/cmake-tools.nvim#124]
**Bug description**
When I'm switching from my main project to another one, the following error is being produced when I'm trying to run `:CMakeGenerate`:
```
|| CMake Error: Unable to (re)create the private pkgRedirects directory:
|| /code/microsar-adaptive/build/CMakeFiles/pkgRedirects
|| Exited with code 1
```
Note that /code/microsar-adaptive is the project I was previously working with and not the project that I'm in right now.

**Steps to reproduce**
I quitted neovim, cded into /code/test-project and run `:CMakeGenerate` inside neovim

Somehow cmake-tools wants to do something here with the wrong directory, even deleting the session file does not help and the same error is still being produced.

**Comment by jla2000** [comment]
It also somehow creates the directory `/code/microsar-adaptive/build` inside `/code/test-project` (probably mkdir -p used) so there is a newly created folder `/code/test-project/code/microsar-adaptive/build` where it tries to run some cmake stuff on

**Comment by jla2000** [comment]
I've also noticed that in `:CMakeSettings` the `vars.dir.build` is set to `/code/microsar-adaptive` and I'm not able to change it to the right directory as the changes get discarded (I ran `:wq`) .

**Comment by Civitasv** [comment]
Can you post the contents of session file?

**Comment by jla2000** [comment]
This is the content of the file for `/code/test-project`

```
return {
  base_settings = {
    env = {},
    working_dir = "${dir.binary}"
  },
  build_directory = "/code/microsar-adaptive/build",
  build_type = "Debug",
  query_directory = "/code/microsar-adaptive/build/.cmake/api/v1/query",
  reply_directory = "/code/microsar-adaptive/build/.cmake/api/v1/reply",
  target_settings = {}
}
```

It contains wrong entries. When I change them to what I suppose to be correct, it will get overriden the next time and has no effect.

**Comment by Civitasv** [comment]
What's the result of `:pwd` in neovim?

**Comment by Civitasv** [comment]
I wonder why `build_directory` is not relative. Are you using preset or kit? Maybe you can check if they contain absolute path.

**Comment by jla2000** [comment]
for the microsar-adaptive I'm using a cmake preset that only contains relative paths, but for the test-project I use the plain cmake debug configuration without any specific preset or kit.

**Comment by Civitasv** [comment]
I cannot reproduce it 🤔, maybe a bug about CMakeSetting.

**Comment by hfn92** [comment]
> Somehow cmake-tools wants to do something here with the wrong directory, even deleting the session file does not help and the same error is still being produced.

Just wondering. Did you close all nvim instances before deleting? Otherwise cmake-tools will just write them back

**Comment by jla2000** [comment]
@hfn92 I will try this, but I'm pretty sure no other instance was running there

**Comment by Civitasv** [comment]
Can you reproduce this bug if you use another cmake project?

**Comment by jla2000** [comment]
There was a wrong entry in the plugin config:
`cmake_build_directory = "/code/microsar-adaptive/build", -- this is used to specify generate directory for cmake`

Somehow the absolute path messed things up here, after removing this it worked fine.

**Comment by Civitasv** [comment]
Yes, it should not be absolute, it should be a relative path.

**Comment by jla2000** [comment]
Okay, I'm closing this then
