### ISSUE TITLE
Check cache files if build directory is removed

### ISSUE THREAD

**Issue by deeedob** [Civitasv/cmake-tools.nvim#125]
Just encountered this: cmake-tools thinks it's in an active environment when a previously active build directory gets suddenly removed.

There was no way for me force it to re-generate. Even with `CMakeGenerate!`. So I had to remove the cache file manually. Perhaps this can be checked?

I used a CMakePresets.json file here and changed the name. Then just deleted the whole build dir.

- OS: Arch Linux
- Plugins commit hash: 20082f85909864a3c93acbc51c20dddc1004f39d

**Comment by Civitasv** [comment]
Can you provide a detailed way to reproduce this problem?

**Comment by Civitasv** [comment]
The latest commit should fix this problem. You should use `CMakeGenerate!` to re-generate.

**Comment by Civitasv** [comment]
Closing now, feel free to open it if you encounter this error again.
