### ISSUE TITLE
No telescope picker:(

### ISSUE THREAD

**Issue by deveezy** [Civitasv/cmake-tools.nvim#127]
Hi, any reason that I see this and not see Telescope picker?
![image](https://github.com/Civitasv/cmake-tools.nvim/assets/80103622/8c2e59a9-7bff-4cf3-9553-a5129ba3285d)

**Comment by Civitasv** [comment]
Currently, Our telescope extension is only used for pick cmake-related files, including source files and CMake configuration files. For others like kits, variants, presets, we use “vim.ui.select”, so you can use a UI enhanced plugin to get result like in the demo.

**Comment by deveezy** [comment]
Oh, thank you)
