### ISSUE TITLE
Issues with :CMakeSelectCwd / finding preset files

### ISSUE THREAD

**Issue by jla2000** [Civitasv/cmake-tools.nvim#129]
**Bug description**
When updating to the latest version with this newly added `:CMakeSelectCwd` feature, I'm no longer able to generate or run anything. The plugin fails to do anything with this error message:
```
Error executing Lua callback: Vim:E484: Can't open file /home/user/code/microsar-adaptive//home/user/code/microsar-adaptive/CMakePresets.json
stack traceback:
	[C]: in function 'readfile'
	...e/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/presets.lua:76: in function 'decode'
	...e/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/presets.lua:105: in function 'parse'
	...hare/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:927: in function <...hare/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:913>
```

Notice that the mentioned path to the CMakePresets.json is not correct anymore here, looks like some broken concatenation.
Deletion of the session file does also not help.

A workaround I found to currently circumvent this is set `:CMakeSelectCwd` to `./`, then it works just fine. (Before it was `/home/user/code/microsar-adaptive`)

**Comment by Civitasv** [comment]
@ErezAmihud Can you see it?

**Comment by jla2000** [comment]
I have found the issue i think

**Comment by ErezAmihud** [comment]
> I have found the issue i think

Can you send your presets file?

**Comment by jla2000** [comment]
@ErezAmihud 
> Can you send your presets file?

I'm don't think so, its not public Xd

Have a look on my pr #130 I think it was an issue there with the path construction of these preset files.

**Comment by jla2000** [comment]
@ErezAmihud 
Basically there was an absolute path constructed and checked and then added to the list of other relative files.
So when constructing the final filename the added files get appended the parent path again

**Comment by jla2000** [comment]
Its merged now, so I'm closing this now

**Comment by ErezAmihud** [comment]
> @ErezAmihud Basically there was an absolute path constructed and checked and then added to the list of other relative paths. So when constructing the final filename the added files get appended the parent path again

Yes, I looked at the pr now, good solution :)
