### ISSUE TITLE
Changing cwd in neovim is not respected

### ISSUE THREAD

**Issue by jla2000** [Civitasv/cmake-tools.nvim#133]
**Bug description**
When opening not directly the project folder, cmake-tools is unable to execute any commands and determine the working directory correctly.

**Steps to reproduce**
```
$ cd ~
$ nvim
:e code/project/CMakeLists.txt
:CMakeGenerate
```
Error message printed: Cannot find CMakeLists.txt at cwd (/home/jla2000).

But when doing it like this:
```
$ cd code/project
$ nvim
:e CMakeLists.txt
:CMakeGenerate
```
it works.

I think probably the working dir is only set when loading the plugin and not changed further when changing directories etc

**Comment by jla2000** [comment]
Actually, I didn't lazy load cmake-tools so it was always loaded on startup.
So a workaround for me is to load it only on cpp and cmake files and make sure the correct working directory is set before.
Anyways I think switching a project should work without quitting / reopening neovim

**Comment by Civitasv** [comment]
You can use the `CMakeSelectCwd` command to switch cwd.
