### ISSUE TITLE
config: cmake_build_options are not added?

### ISSUE THREAD

**Issue by Arniiiii** [Civitasv/cmake-tools.nvim#134]
How to reproduce? 

1. take an example configuration from README
2. write something like this 
```
  cmake_build_options = { "--parallel", "12" }, -- this will be passed when invoke `CMakeBuild`
```
or this:
```
  cmake_build_options = { "--parallel 12" }, -- this will be passed when invoke `CMakeBuild`
```
or this:
```
  cmake_build_options = { "-j12" }, -- this will be passed when invoke `CMakeBuild`
```
or this:
```
  cmake_build_options = { "-j 12" }, -- this will be passed when invoke `CMakeBuild`
```
or this: 
```
  cmake_build_options = { "-j", "12" }, -- this will be passed when invoke `CMakeBuild`
```
then: 
```
:CMakeBuild
```

and the build doesn't look like it's paralled. also, the command line args which I see doesn't show the argument.
Also, if try adding `--verbose` it doesn't add it too.

It's not the problem with connecting the plugin configuration ( CMakeDebug with specific settings somehow works.. )

tested:
commit:  9136be8

**Comment by Civitasv** [comment]
This is because we support `session`, it will firstly read `cmake_build_options` from session file if it exists. Maybe you generate this session file with previous version of `cmake-tools.nvim`.

You can:

1. Type `CMakeSettings`
2. Fill "-j12" in the `build_options` field.

**Comment by Gerodote** [comment]
Thanks!
