### ISSUE TITLE
config: cmake_kits_path is not working properly

### ISSUE THREAD

**Issue by Gerodote** [Civitasv/cmake-tools.nvim#142]
steps to reproduce:

1. get a CMakeKits file e.g. from VS Code -> CMake Tools -> Scan kits
2. get them as a file ( usually at `/home/*/.local/share/CMakeTools/cmake-tools-kits.json` on linux )
a. put the file at project's folder and selecting kit works properly ( Thanks ! )
b. put the path to the file into the config and get next:

all kits are visible at `:CMakeSelectKit`  but when you choose anything, the `c++` ( /usr/bin/c++ ) compiler is working, not `clang++-16` or `gcc-12` or whatever -> I assume that the way doesn't work .

Checked commit : some of the previous ones and the last one too : a355bee

**Comment by Civitasv** [comment]
Is there any error message?

**Comment by Gerodote** [comment]
I see no error message. 

maybe the problem is that the file is not named like CMakeKits.json or smth like, I'll check a little bit later

**Comment by Gerodote** [comment]
It doesn't depend on name. 

How I checked: 
```
cd ~
ln -s ~/.local/share/CMakeTools/cmake-tools-kits.json CMakeKits.json
```
Got to config, changed the path from `~/local/share/CMakeTools/cmake-tools-kits.json` to `/home/user_name/CMakeKits.json`
Erased cache : `rm ~/.cache/cmake_tools_nvim/* `
Tested. Got the same problem

Done the same with `ln -s ~/.local/share/CMakeTools/cmake-tools-kits.json cmake-kits.json ` 
Got the same problem

**Comment by Civitasv** [comment]
How do you know that you are using `/usr/bin/c++` instead of `clang++-16`?

**Comment by Gerodote** [comment]
`--verbose` at build give me output of how a compile command looks like. 
also, at configuring usually it's written something like `"Checking C++ compiler : c++ " ` or `Checking C++ compiler: clang-16++` or something similar. 
Another way is to configure, then in another terminal:
```
cd project_folder
ccmake -S . -B ./cmake_build_specific_folder
```
Then, press `t` to toggle advanced mode. There's usually path to C and C++ compiler: `CMAKE_C_COMPILER` and `CMAKE_CXX_COMPILER` respectively. Tip: if you change there it to clang and clang++, all other variable that are important will change automatically, such as putting `llvm-ar`, `llvm-nm`, `llvm-ranlib` and so on. Though, it won't turn on libc++ or compiler-rt : for this add compile flag `-stdlib=libc++` and at  linker flags add next: `-compiler-rt` .

**Comment by Civitasv** [comment]
I've pushed a fix, now it should work.

**Comment by Gerodote** [comment]
Yep, thanks to you !
