### ISSUE TITLE
wrong CMakePresets.json file path

### ISSUE THREAD

**Issue by AbdelghaniDr** [Civitasv/cmake-tools.nvim#143]
**Bug description**
When there is a `CMakeUserPresets.json` file present in the project's root directory that includes another `CMakePresets.json` file from another directory (a child directory in the build folder for example), if the path is **absolute**, the plugin does not compose the correct path but just concatenates the two strings representing the paths, i.e, _the root project directory absolute path_ and the _absolute path for the included `CMakePresets.json` file_ and we end up with a string like **/home/user/projects/project1//home/user/projects/project1/build/CMakeUserPresets.json** which is not correct and causes a `can't open file` error when we call `CMakeSelectBuildPreset`.  

**Steps to reproduce**
1- directory structure:
```
 project1/
     CMakeUserPresets.json
     CMakeLists.txt
     main.cpp
     build/
        CMakePresets.json
```
2- content of the file CMakeUserPresets.json:
the file is auto generated by conan package manager
```
{
    "version": 4,
    "vendor": {
        "conan": {}
    },
    "include": [
        "/home/user/projects/project1/build/CMakePresets.json". <- note the absolute path here
    ]
}

```

**Expected behavior**
check if the paths are _absolute_ or _relative_ and compose the correct final path

**Environment**

- OS: Centos Linux

**Comment by Civitasv** [comment]
Please also post the stacktrace.

**Comment by Civitasv** [comment]
I've pushed a fix. Can you check it?

**Comment by AbdelghaniDr** [comment]
it looks like it's fixed now, the plugin can open the included `CMakePresets.json` correctly, thanks
