### ISSUE TITLE
CMakeOpen doesn't work

### ISSUE THREAD

**Issue by MKrbm** [Civitasv/cmake-tools.nvim#144]
When try to use `CMkaeOpen` I got 
![image](https://github.com/Civitasv/cmake-tools.nvim/assets/57752203/17d48525-fc8f-4834-a42b-bdbfec35eeed)

This. 

I think all comands except this works fine so far. Thank you

**Comment by MKrbm** [comment]
I'm using the folk of `NvChad` [my repo](https://github.com/MKrbm/mynvchad.git). But I found this can happens in different settings.

I use default settings. What I did was just add "nvim-lua/plenary.nvim" into `dependencies` field and install via Lazy.

**Comment by Civitasv** [comment]
Okay, closing now. Feel free to open it if you encounter this issue again.
