### ISSUE TITLE
support overseer for terminal handling

### ISSUE THREAD

**Issue by hfn92** [Civitasv/cmake-tools.nvim#145]
**Describe the problem or limitation you are having**
I find the terminal a bit intrusive. I'd prefer it to only show up when I want to.

**Describe the solution you'd like**
I wanted to see I if can adapt it to optionally run in a toggleable floating window. But I saw the new executor feature which supports overseer. It seems this only works for quickfix tough. Would it be possible to support this for the terminal as well. I think this would satisfy my use-case and even more.

**Comment by rohit-kumar-j** [comment]
~How dare you... I feel attacked~ 😂 JK

Me and @Civitasv are currently developing the experimental terminal.

I share your sentiment for terminal, I think the existing terminal buffer options can have better windowing functionality, finetuning and setup instructions in the docs.

Do you suggest a togglable floating window like in [toggleterm](https://github.com/akinsho/toggleterm.nvim)?

I haven't dabbled with overseer at all, could give me an example project/config/setup/set of commands for overseer for this?

**Comment by hfn92** [comment]
@rohit-kumar-j feel free to check out my fork here https://github.com/hfn92/cmake-tools.nvim/tree/overseer_terminal

This runs every cmake-tools command through overseer.  Overseer will show a notification if a command fails. I then open the output in a floating window to look at it. 

I use following keybindings
```lua
      ["<leader>of"] = { "<CMD> OverseerQuickAction open float<CR>", "Overseet open float " },
      ["<leader>oh"] = { "<CMD> OverseerQuickAction open hsplit<CR>", "Overseet open hsplit" },
      ["<leader>ov"] = { "<CMD> OverseerQuickAction open vsplit<CR>", "Overseet open vsplit" },
      ["<leader>oq"] = { "<CMD> OverseerQuickAction open output in quickfix<CR>", "Overseet open quickfix" },
      ["<leader>oo"] = { "<CMD> OverseerToggle<CR>", "Overseet toggle" },

```

**Comment by rohit-kumar-j** [comment]
@hfn92 , I haven't fully dived deep into overseer, but does overseer have an inbuilt terminal mode?

**Comment by Civitasv** [comment]
Thanks for @rohit-kumar-j review of overseer.nvim. I also have a quick look for this plugin. Here is my conclusion.

Firstly, the **design purpose** of our own terminal is to provide a unified location for executing commands, so we can persistent env vars, store all commands that have been executed, give full access to the user (users who do not use CMakePresets) to set/modify specific cmake flags, support stdin, etc, as said by @rohit-kumar-j. The core idea is: when there is a terminal, we don't make a new one.

And, the **design purpose** of overseer.nvim is to provide a unified task runner and job management plugin for Neovim. It supports multiple ways to run commands, including terminal, plenary, toggleterm, etc.

> The default, terminal, takes the task cmd and passes it to vim.fn.termopen().

However, when overseer.nvim execute the commands, it doesn't reuse the terminal. So, it cannot be a replacement for our own terminal, but can be a replacement for the quickfix.

Back to your problem, I admit it is reasonable if you only wanna use one method to configure, build, clean, and even execute the executable programs, it is cleaner. Here is my solution for it.

0. We should split the cmake process to two parts, one for generating libraries and executable, one for executing the executable programs.
1. For the former, we use **Executor**, including overseer.nvim, quickfix, and terminal.
2. For the latter, we use **Runner**, also including overseer.nvim, quickfix, and terminal.

Thus, users can freely choose the executor and runner. I think this can satify most people's need.

And, we should provide more functionalities for our terminal, including toggle window, resize window, float window, etc. @rohit-kumar-j.

What do you think? @hfn92 @rohit-kumar-j

**Comment by Civitasv** [comment]
Okay, I understand. I will start implementing it when I have time, recently I'm busy with finding jobs 😃.

**Comment by athanase** [comment]
I think @Civitasv approach of having Executors and Runners and giving the choice to the user on which back-end is used would be really useful.

**Comment by hfn92** [comment]
> Okay, I understand. I will start implementing it when I have time, recently I'm busy with finding jobs 😃.

Sounds good. I hope your job search goes well :+1:

**Comment by rohit-kumar-j** [comment]
> 0. We should split the cmake process to two parts, one for generating libraries and executable, one for executing the executable programs.
> 1. For the former, we use **Executor**, including overseer.nvim, quickfix, and terminal.
> 2. For the latter, we use **Runner**, also including overseer.nvim, quickfix, and terminal.

Sounds good. I think this will take some time 😅 though.

**Comment by Civitasv** [comment]
> Sounds good. I think this will take some time 😅 though.

Yes, applying a job is hard for me. 😢

**Comment by Civitasv** [comment]
I've implemented this *Executor* and *Runner* logic, you can use the latest commit. See if everything is okay.

**Comment by hfn92** [comment]
@Civitasv thanks for implementing this :) 

regular `CMakeRun` works fine for me. I just had to change the default strategy from `toggleterm` to `terminal` since I don't have `toggleterm` installed. Maybe `terminal` should be default?

Other than that I now have some issues with `CMakeDebug` and `CMakeQuickRun` (possibly `CMakeQuickDebug` too). Not sure if these are regressions or my config is outdated :sweat_smile: 

`CMakeDebug` 
```lua
Error executing vim.schedule lua callback: ...hare/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:848: attempt to call field 'close' (a nil value)
stack traceback:
	...hare/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:848: in function 'callback'
	...hare/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:406: in function 'on_success'
	...are/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/utils.lua:246: in function 'on_exit'
	.../nvim/lazy/cmake-tools.nvim/lua/cmake-tools/quickfix.lua:90: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

`CMakeQuickRun` no longer seems to pass the configured argument the the executable regardless of whether `overseer`  or `terminal` is configured as `cmake_runner`

**Comment by Civitasv** [comment]
Pushed a fix.

**Comment by athanase** [comment]
@Civitasv thanks a lot, it works perfectly fine for me !

**Comment by hfn92** [comment]
> Pushed a fix.

thanks, debugging works now :+1: 


For `CMakeQuick*` argument passing, I propose:
```
diff --git a/lua/cmake-tools/init.lua b/lua/cmake-tools/init.lua
index 3f69d1d..a03c72d 100644
--- a/lua/cmake-tools/init.lua
+++ b/lua/cmake-tools/init.lua
@@ -585,7 +585,7 @@ function cmake.run(opt)
           target_path,
           config.env_script,
           env,
-          opt.args,
+          opt.args and opt.args or config.target_settings[opt.target].args,
           launch_path,
           config.runner,
           nil,
@@ -799,7 +799,7 @@ if has_nvim_dap then
           name = opt.target,
           program = result.data,
           cwd = cmake.get_launch_path(opt.target),
-          args = opt.args,
+          args = opt.args and opt.args or config.target_settings[opt.target].args,
           env = env,
         }
         -- close cmake console
```
I think that should fix it

**Comment by Civitasv** [comment]
Thanks, I've pushed a fix.
