### ISSUE TITLE
Toggle cmake_terminal

### ISSUE THREAD

**Issue by athanase** [Civitasv/cmake-tools.nvim#151]
**Describe the problem or limitation you are having**

While developing, I regularly toggle between the build terminal (in the quickfix list for this plugin) in a bottom window and also the launch terminal (here the [CMakeTools] terminal) in the same area. I currently use overseer which has a window displaying all tasks (build, run, ...) and [edgy](https://github.com/folke/edgy.nvim) to either have nothing open, or the quickfix window, or the tasklist.

I am most certainly missing something but I cannot find a way to toggle the `cmake_terminal` and also close it easily ?

**Describe the solution you'd like**

Preferred solution would be to have a way to hide/unhide/close the `cmake_terminal` easily ?
Or maybe have different execute strategy for the target runner (e.g. overseer or toggleterm instead of cmake_terminal) ? 

**Describe alternatives you've considered**

I am currently able to do this when I use overseer as it can be used to build or launch programs, and I can view it in the same tasklist pane. 

**Additional context**

Awesome plugin. Really waiting for the integration for the Test Framework integration.

**Comment by rohit-kumar-j** [comment]
Related #145

**Comment by rohit-kumar-j** [comment]
> **Describe the problem or limitation you are having**
> 
> While developing, I regularly toggle between the build terminal (in the quickfix list for this plugin) in a bottom window and also the launch terminal (here the [CMakeTools] terminal) in the same area. I currently use overseer which has a window displaying all tasks (build, run, ...) and [edgy](https://github.com/folke/edgy.nvim) to either have nothing open, or the quickfix window, or the tasklist.

Yes, currently there is no extensive terminal window handling for the `terminal executor` it can only be opened by running a `:CMake<...>` command. I think support for this can eventually be added.(`:CMakeOpen` and `:CMakeClose` support rudimentary open-close logic, but only for current terminal, not all open cmake terminals)

> I am most certainly missing something but I cannot find a way to toggle the `cmake_terminal` and also close it easily ?
>
> **Describe the solution you'd like**
> 
> Preferred solution would be to have a way to hide/unhide/close the `cmake_terminal` easily ? Or maybe have different execute strategy for the target runner (e.g. overseer or toggleterm instead of cmake_terminal) ?

If having a layout is necessary, we can try integrating edgy, with sessions (probably won't work unless all terminal buffers are pre-opened upon startup ... not ideal ... as there might be several open terminals from the previous session and would need to be reopened upon startup(?) ... not sure how to go about this, @Civitasv)

or/and

provide a telescope-picker for selecting from a list of terminals that the user can pick, like `:Telescope find_files` or  `:Telescope live_grep`, but for cmake terminals with `vim.ui.select` , which the user can setup how they like(might not be default, or might have another option name)

> **Describe alternatives you've considered**
> 
> I am currently able to do this when I use overseer as it can be used to build or launch programs, and I can view it in the same tasklist pane.

For tasklist pane integration into terminal executor, see #145

**Comment by Civitasv** [comment]
See https://github.com/Civitasv/cmake-tools.nvim/issues/145#issuecomment-1863761682
