### ISSUE TITLE
Error when exit the terminal with non-zero status and rerun `CMakeRun`

### ISSUE THREAD

**Issue by v1nh1shungry** [Civitasv/cmake-tools.nvim#153]
**Bug description**

Error occurs when exit the terminal with non-zero status and rerun `CMakeRun`

**Steps to reproduce**

<details>
  <summary>Click me</summary>

  ```lua
  require("cmake-tools").setup {
    cmake_generate_options = { '-G', 'Ninja', '-DCMAKE_EXPORT_COMPILE_COMMANDS=On' },
    cmake_build_directory = 'build',
    cmake_soft_link_compile_commands = false,
    cmake_terminal = {
      opts = {
        start_insert_in_launch_task = true,
        focus_on_launch_terminal = true,
      },
    },
  }
  ```
</details>

1. `CMakeRun` to run a program returning non-zero status.
2. Type `exit` in the terminal to close the terminal.
3. Rerun `CMakeRun`, an error occurs:
```
Error executing vim.schedule lua callback: .../cmake-tools.nvim/lua/cmake-tools/executors/terminal.lua:176: Invalid window id: -1
stack traceback:
	[C]: in function 'nvim_set_current_win'
	.../cmake-tools.nvim/lua/cmake-tools/executors/terminal.lua:176: in function 'send_data_to_terminal'
	.../cmake-tools.nvim/lua/cmake-tools/executors/terminal.lua:507: in function 'execute'
	...are/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/utils.lua:78: in function 'execute'
	...hare/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:586: in function 'callback'
	...hare/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:364: in function 'on_success'
	...are/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/utils.lua:167: in function 'on_exit'
	.../nvim/lazy/cmake-tools.nvim/lua/cmake-tools/quickfix.lua:79: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Expected behavior**

No error.

**Screenshots**

![](https://github.com/Civitasv/cmake-tools.nvim/assets/98312435/096c9d6f-76c1-408b-8122-c89977e082f7)

**Environment**

- OS:  Ubuntu
- Desktop environment:  Gnome
- Plugins commit hash:  86bad7cb3ebc1cac51046e88cf62d5b962e8a1cc

**Additional context**
<!-- Add any other context about the problem here. --

**Comment by Civitasv** [comment]
You should close the terminal buffer, for me, I just click `return`. Else we will try to send data to the exited terminal.

**Comment by v1nh1shungry** [comment]
> You should close the terminal buffer

Okay, it works. I thought it is a bug because doing the same operation when the program returns `0` won't panic. And I still think it's great if it won't panic when the program returns non-zero value too.

> for me, I just click `return`.

Sorry I don't understand what `return` is. Is that a key?

Anyway, thank you for the reply and the plugin!
