### ISSUE TITLE
Different build folders for each kit

### ISSUE THREAD

**Issue by athanase** [Civitasv/cmake-tools.nvim#154]
**Describe the problem or limitation you are having**

I often switch between different compilers and thus I have different kits (e.g. gcc, clang, cross compilation with clang-cl and cross-compilation with MSVC).

When building/running with a specific kit, in Debug mode for example and then switching the kit, I have to cleanup the corresponding debug build folder and reconfigure and then reconfigure/build/run.

This is a tedious workflow when you want to compare behaviors between two different compilers for example.

**Describe the solution you'd like**

Create a root build folder for each kit, or identify each kit in the name of the build folder.

- build_mscv_Debug
- build_mscv_Release
- build_clang_Debug

or

- build_msvc
    - Debug
    - Release 
- build_clang
    - Debug

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by rohit-kumar-j** [comment]
Is this is standard [cmake-tools](https://github.com/microsoft/vscode-cmake-tools) feature?

**Comment by athanase** [comment]
It does seem so via the use of variables, e.g.: ${buildKit}

[](https://github.com/microsoft/vscode-cmake-tools/issues/151)

**Comment by rohit-kumar-j** [comment]
I'm not sure which would be the best method to do this. In addition to the variations mentioned above, I can think of a few more...


```bash
#1
* build_mscv_Debug
* build_mscv_Release
* build_clang_Debug

#2
* build_msvc
    * Debug
    * Release
* build_clang
    * Debug
    * Release
    
######

#3
* build
    * mscv_Debug
    * mscv_Release
    * clang_Release

#4
* build-debug
    * clang
    * msvc
    * gcc
* build-release
    * clang
    * msvc
```

I think we should give users the ability to configure it themselves, however, a reasonable default should be to not pollute the root directory of the user with `\build-abc` to `\build-xyz`, so maybe `#2` or `#3` might be good alternative.

Also, [there seem to be complications](https://stackoverflow.com/questions/5728116/can-i-link-object-files-made-by-one-compile-to-those-made-by-another-one) when builds from different compilers are linked together based on ABI compatibility. So, I'm not sure if `#4` might not be a good idea for a folder structure.

**Comment by rohit-kumar-j** [comment]
@Civitasv, what do you think of this?

**Comment by Civitasv** [comment]
Maybe we should allow macro expansion for `cmake_build_diretory`, like https://github.com/microsoft/vscode-cmake-tools/issues/151#issuecomment-532416210.

For example:

> "cmake.buildDirectory": "${workspaceRoot}/build/${buildKit}/${buildType}"

**Comment by Civitasv** [comment]
I've managed to support macro expansion for `cmake_build_directory`, see the latest commit. Now it supports:

1. ${kit} -> kit.name
2. ${kitGenerator} -> kit.generator
3. ${variant:xx} -> choice of variant.xx (the short message)

An example: `out/${variant:buildType}/${kit}/${kitGenerator}`

**Comment by athanase** [comment]
Thanks a lot @rohit-kumar-j  and @Civitasv for quickly adding support for this. 
This perfectly answers my use cases and it is customizable enough for other use cases.
