### ISSUE TITLE
Latest commit causes the plugin not to work

### ISSUE THREAD

**Issue by MiliAxe** [Civitasv/cmake-tools.nvim#156]
**Bug description**
I'm a new user to this great plugin however after installing it for the first time. After installing for the first time. I noticed that the plugin is barely functioning. Every command would not work. for Example, `CMakeGenerate` would give the following error:
```
Error executing Lua callback: ...pack/lazy/opt/cmake-tools.nvim/lua/cmake-tools/utils.lua:219: bad argument #1 to 'ipairs' (table expected, got nil)
stack traceback:
        [C]: in function 'ipairs'
        ...pack/lazy/opt/cmake-tools.nvim/lua/cmake-tools/utils.lua:219: in function 'prepare_build_directory'
        .../pack/lazy/opt/cmake-tools.nvim/lua/cmake-tools/init.lua:237: in function <.../pack/lazy/opt/cmake-tools.nvim/lua/cmake-tools/init.lua:106>
```

**Steps to reproduce**
Install the commit 0add90e46007d5be9e3584211c6c75d080f098ab
Try any command

**Expected behavior**
Commands working as expected

**Environment**

- OS: <!-- Arch Linux
- Desktop environment: i3
- Plugins commit hash: 0add90e46007d5be9e3584211c6c75d080f098ab

**Comment by MiliAxe** [comment]
It is worth mentioning that reverting back to the commit a3636dae9aeb90234c6d5d167c4a55d54899bad8
makes the plugin function as expected

**Comment by Civitasv** [comment]
Thanks, I've pushed a fix.
