### ISSUE TITLE
Unintuitive overwriting of the config options by cached session config

### ISSUE THREAD

**Issue by extramask93** [Civitasv/cmake-tools.nvim#162]
**Describe the problem or limitation you are having**
When modifying config which is supplied to the init.setup function with a new option such as:
`require("cmake-tools").setup({
...
 cmake_generate_options={ ..., "-DFOO=1"},
...
})`
The new option won't be loaded when there already exist a cache for a given project. Seemingly thanks to this line in init.lua:
`
config.base_settings =
        vim.tbl_deep_extend("keep", old_config.base_settings, config.base_settings)
`
This was confusing for a new user (me) and forced me to investigate it in the code. 
**Describe the solution you'd like**
Don't know if it is an intended behavior, if it is really so, then it would be worth mentioning it (highlighted) in the config
section of README. 

**Describe alternatives you've considered**
vim.tbl_deep_extend("force", old_config.base_settings, config.base_settings)

**Additional context**

**Comment by rohit-kumar-j** [comment]
Interesting. I think this might have been the real cause of the problem I was facing with windows in #146. Feel free to create a PR :D

**Comment by Civitasv** [comment]
I understand your concern. Currently, for a new project, it will firstly initialize a session file which include `generate_options`, `build_options`, `build_dir` etc. Then, if you open this project again, if will reuse this session file.

**Comment by Civitasv** [comment]
Closing for now, feel free to open it if you still have this problem.
