### ISSUE TITLE
CMakeGenerate mkdir error on Windows OS

### ISSUE THREAD

**Issue by Julpikar** [Civitasv/cmake-tools.nvim#163]
**Bug description**
Can't generate CMakeGenerate after commit newer than 86bad7cb3ebc1cac51046e88cf62d5b962e8a1cc: 
<code>Error executing Lua callback: ...a/Local/nvim-data/lazy/plenary.nvim/lua/plenary/path.lua:505: We couldn't mkdir: C:\testing\cpptest\out/Debug
stack traceback:
        [C]: in function 'error'
        ...a/Local/nvim-data/lazy/plenary.nvim/lua/plenary/path.lua:505: in function 'mkdir'
        ...im-data/lazy/cmake-tools.nvim/lua/cmake-tools/config.lua:64: in function 'generate_build_directory'
        ...nvim-data/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:245: in function <...nvim-data/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:106></code>

**Steps to reproduce**

<details><summary>Minimal configuration</summary>
<code>require("cmake-tools").setup({
          cmake_soft_link_compile_commands = false,
          cmake_compile_commands_from_lsp = true,
        })
</code>
</details>

**Expected behavior**
CMakeGenerate worked.

**Environment**

- OS: Windows
- Plugins commit hash: 50012918b2fc8357b87cff2a7f7f0446e47da174

**Comment by rohit-kumar-j** [comment]
I cannot seem to reproduce this on windows.

**Comment by Julpikar** [comment]
I just trying to debug plenary path:new and path:mkdir. It seem can't create new folder in windows if path using / like "C:\testing\cpptest\out/Debug". if you change path using \ like "C:\testing\cpptest\out\Debug", then it's succed created folder.

**Comment by Julpikar** [comment]
I just trying to debug plenary path:new and path:mkdir. It seem can't create new folder in windows if path using / like "C:\testing\cpptest\out/Debug". if you change path using \ like "C:\testing\cpptest\out\Debug", then it's succed created folder.

**Comment by Julpikar** [comment]
It's work now, just using custom configuration `cmake_build_directory = "out\\${variant:buildType}"`. Thank for usefull plugin and team response.
