### ISSUE TITLE
CMakeSettings change not saved

### ISSUE THREAD

**Issue by Tomobodo** [Civitasv/cmake-tools.nvim#164]
**Bug description**
It seems the change i'm making in the CMakesettings popup are not saved.
I wanted to use it to specify different output directory based on my buildType.
Whenever I run CMakeSettings, make some changes, close the popup and reopen it, no change are saved.

**Steps to reproduce**

- Make a simple cpp hello world project using cmake.
- create a build/debug folder.
- Run CmakeSettings and set the build path to "/home/user/projectpath/build/debug"
- escape
- rerun CMakeSettings to see if change are still here, i have no change saved.

**Expected behavior**
When reoppening the CMakeSeettings popup i expect to see my previous change

**Environment**

- OS: Debian 12
- Desktop environment: Gnome
- Plugins commit hash: 4b7a0e79cb72ca01a3106987be45961b5f2dddb6

**Comment by Tomobodo** [comment]
OK completly my bad for misunderstanding vars are not modifiable i wish i could delete that issu.

**Comment by Civitasv** [comment]
That's okay. :smile:
