### ISSUE TITLE
Cannot Load config.icons, readme needs update to make instructions clearer

### ISSUE THREAD

**Issue by ihersom** [Civitasv/cmake-tools.nvim#165]
Not sure what I am doing wrong but I get an error trying to use the lualine status bar, I am new to lua and not entirely sure what to do with this file from https://github.com/Civitasv/runvim/blob/master/lua/config/icons.lua - I tried setting the require("") to the absolute path of this lua file, that did not work.

**Comment by rohit-kumar-j** [comment]
I don't think you need the absolute path. It is generally loaded as a module. [Similar](https://github.com/rohit-kumar-j/nvim/blob/8a26137bb64592fc2bbf6844b8b2ef93e67def67/lua/core/plugin_config/lualine.lua#L12)

**Comment by Civitasv** [comment]
Yes, you just need to load it as a module.

**Comment by Civitasv** [comment]
Closing it for now, feel free to open it if you still have problem.
