### ISSUE TITLE
BUG1: config support pathes with ~ BUG2: `:CMakeRun` bug : path is not in quotes .

### ISSUE THREAD

**Issue by Gerodote** [Civitasv/cmake-tools.nvim#166]
**Bug description**

just check screenshots

**Steps to reproduce**

<details><summary>Minimal configuration</summary>
</details>

1. vs code -> cmake tools -> scan kits -> yay, you got `~/.local/share/CMakeTools/cmake-tools-kits.json`

2. put the path to config ( here's a _BUG 1_: you cannot put path with ~  like `~/.local/share/CMakeTools/cmake-tools-kits.json` , you should write smth like `/home/fuxu/.local/share/CMakeTools/cmake-tools-kits.json` at `cmake_kits_path` at config) or `ln -s ~/.local/share/CMakeTools/cmake-tools-kits.json ./` at your project folder

3. nvim -> `:CMakeRun` -> _BUG 2_ if kit name has spaces ( like `Clang 16.0.6 x86_64-pc-linux-gnu`), command to run target fails. 

**Screenshots**

# BUG 1:
![image](https://github.com/Civitasv/cmake-tools.nvim/assets/58738099/9f44da55-00d9-4926-b59e-c75395b51631)
![image](https://github.com/Civitasv/cmake-tools.nvim/assets/58738099/244dac3c-fa8b-497d-bceb-7fa73428513a)
![image](https://github.com/Civitasv/cmake-tools.nvim/assets/58738099/5cd316a6-113c-43b7-8ba2-890903900d48)

### `:CMakeGenerate`

![image](https://github.com/Civitasv/cmake-tools.nvim/assets/58738099/6ac7fd8b-afb6-4e91-9c8e-3c7bc9c80825)

# BUG 2:
![image](https://github.com/Civitasv/cmake-tools.nvim/assets/58738099/3aeffde6-4fa2-4ea3-b5b7-cc79a3d60114)
![image](https://github.com/Civitasv/cmake-tools.nvim/assets/58738099/5302230a-c6fe-4329-a45d-3ffb1bc08525)

**Environment**
neovim 0.9.2
last update of the plugin. [4b7a0e7](https://github.com/Civitasv/cmake-tools.nvim/commit/4b7a0e79cb72ca01a3106987be45961b5f2dddb6)

**Comment by Civitasv** [comment]
Can you share your configuration?

**Comment by Civitasv** [comment]
For BUG2, the problem is that `Clang 16.0.6 x86_64-pc-linux-gnu` has whitespaces.

**Comment by Gerodote** [comment]
> Can you share your configuration?

I think there's at the screenshot much of the config ( basically copy paste default + insert it in Lazy ). Line 13 at the first screenshot is the problem. If put there path with `~` it fails.

> For BUG2, the problem is that `Clang 16.0.6 x86_64-pc-linux-gnu` has whitespaces.

Yes, and that should not be a problem, as far linux and windows (and maybe other OSes, idk honestly ) have support for spaces in a path.

I guess, if we can somehow put the path into a quotes, most shell will agree to understand what the command means.

**Comment by Civitasv** [comment]
Use the latest commit, it should work.

**Comment by Gerodote** [comment]
Bug 1 fixed ! Thanks !!!

Bug 2 still in place :
![image](https://github.com/Civitasv/cmake-tools.nvim/assets/58738099/95b28220-66bf-4868-a37d-87388fd54ab1)

**Comment by Civitasv** [comment]
Fixed, use the latest commit.

**Comment by Gerodote** [comment]
It works, thank you!
