### ISSUE TITLE
How to set source directory?

### ISSUE THREAD

**Issue by Gerodote** [Civitasv/cmake-tools.nvim#167]
**Describe the problem or limitation you are having**

There's a project template: [modern cpp starter](https://github.com/TheLartians/ModernCppStarter) 

It has folder `all` for all targets.
I want to set source directory for cmake as `all` to get `compile_commands.json` for folder `all`.
And I don't want to change build directory and keep it as in config set. ( `/project/path/build`  , `build` specified at config as `cmake_build_directory`. )

Lurked something from docs, issues #100 and #164 
1. About working directory 
from docs:

> ### `working_directory`
> 
> Specify the working directory in which run and debug commands are executed. Supports substitution commands (`${}`).
> 
> ```lua
>   working_directory = "${dir.binary}"
> ```
> 
> | Command               | Supported          | Details                 |
> |--------------         | --------------     |  --------------         |
> | `CMakeSettings`       | :white_check_mark: | Defines the working directory for all targets unless overwritten. |
> | `CMakeTargetSettings` | :white_check_mark: | Sets the working directory just for this target. No default value - Has to be added manually. |
> 

ok, It's possible to set folder from which binary is executed

Reading #100 got me to conclusion, that I can somehow specify smth in settings of the project. I tried some stuff in `~/.cache/cmake_tools_nvim/project_path` , tried some stuff in `:CMakeSettings` and nothing worked.

After looking for a command and #164 
I thought `:CMakeSelectCwd` will help. 

Yes, it helped, but not as I expected:
 - yes, source folder now is `/path/to/project/all`
 - not as I expected: base build folder now is `/path/to/project/all/build` .

**Describe the solution you'd like**

Please, explain one of the stuff:
1. How to select build folder? Then it's possible to `:CMakeSelectCwd` and then specify build folder.
2. How to select source folder? Then it's possible to just open project folder with nvim and then specify source folder
3. How to select source and build folder? Then it's possible to do some really interesting stuff.

**Comment by Civitasv** [comment]
Currently, build folder(which specified by `cmake_build_directory`) is relative to cwd(which specified by `: CMakeSelectCwd`), so you can set `cmake_build_directory` to `../out/${variant:buildType}`, then it can satify your needs.

**Comment by Gerodote** [comment]
> > * How to select build folder? Then it's possible to `:CMakeSelectCwd` and then specify build folder.
> > * How to select source folder? Then it's possible to just open project folder with nvim and then specify source folder
> > * How to select source and build folder? Then it's possible to do some really interesting stuff.
> 
> Firstly, update to the latest commit, then:
> 
>     1. To select build folder, use `CMakeSelectBuildDir` or directly change `build_dir` field in `CMakeSettings` window.
> 
>     2. To select source folder, use `CMakeSelectCwd`.
> 
> 
> Here is also a video showcase(apologize for the lower quality of the video; unfortunately, I can only upload videos that are less than 10MB in size.):
> Untitled2.mov

THAT'S AWESOME ! Great work! Thank you so much for this!
