### ISSUE TITLE
User events for when cmake project is detected

### ISSUE THREAD

**Issue by TheCycoONE** [Civitasv/cmake-tools.nvim#169]
**Describe the problem or limitation you are having**
I want to run some autocommands to set key bindings specifically for cmake projects, to call e.g. CMakeDebug instead of my usual dap launcher.

**Describe the solution you'd like**
When the cwd is detected to be a cmake project, call [nvim_exec_autocmds](https://neovim.io/doc/user/api.html#nvim_exec_autocmds()) with a User event and a pattern like `CMakeToolEnterProject`.

**Describe alternatives you've considered**
I can register my keys based on the path instead for each CMake project individually.

**Additional context**
https://itmecho.com/blog/neovim-lua-hooks-with-user-events

**Comment by TheCycoONE** [comment]
Another alternative is to accept a list of keybindings in the setup configuration like nvim-cmp does.

**Comment by TheCycoONE** [comment]
Currently using this workaround:
```
vim.keymap.set('n', '<F5>', function()
  local cmake = require('cmake-tools')
  if cmake.is_cmake_project() then
    cmake.debug({})
  else
    require('dap').continue()
  end
end)
```

**Comment by tan-wei** [comment]
I think another event should be provided: CMakeCwdChanged. Now if CWD is changed, session is not stored automatically. If the event is given, we could use this event to resetup camke-tools to enable it (or any other behaviors).

**Comment by Civitasv** [comment]
I've supported this feature, use the latest commit. For your need, you can define an autocmd like:

```lua
vim.api.nvim_create_autocmd("User", {
  pattern = "CMakeToolsEnterProject",
  callback = function(event)
    vim.keymap.set("n", "<F5>", function() ... end)
  end
})
```

**Comment by Civitasv** [comment]
Closing for now, feel free to open it if you still have this problem.
