### ISSUE TITLE
If CMakeSelectCwd is executed to select another dirctory, the session is not saved

### ISSUE THREAD

**Issue by tan-wei** [Civitasv/cmake-tools.nvim#172]
See [here](https://github.com/Civitasv/cmake-tools.nvim/blob/4b965b5785776b6d258d57ce8fb7efa1a8170a7b/lua/cmake-tools/init.lua#L1515), the session is saved only if:
  - It is a CMake Project at the time cmake-tools.nvim setups

So if we try to use `CMakeSelectCwd` to choose another directory (which means at the setup time, it is not a cmake project), it will be never save the session. But I think the situation is excactly the one we should use session to help use save the "CWD".

**Comment by Civitasv** [comment]
Fair enough, we should support this.

**Comment by tan-wei** [comment]
Wow, good news.

**Comment by Civitasv** [comment]
Pushed a fix, now we support this.

**Comment by Civitasv** [comment]
Closing for now, feel free to open it if you still have this problem.

**Comment by tan-wei** [comment]
Great. I'll try.
