### ISSUE TITLE
Is it possible to add encoding conversion options to the output of QuickFix?

### ISSUE THREAD

**Issue by ck961018** [Civitasv/cmake-tools.nvim#173]
### **Describe the problem or limitation you are having**
At times, I engage in development on a computer with the encoding set to GBK. During such instances, the output of QuickFix appears as garbled characters.
<img width="868" alt="image" src="https://github.com/Civitasv/cmake-tools.nvim/assets/36103557/d3298abc-eeea-4e5f-947a-b3abf2632365">

### **Describe the solution you'd like**
Adding a simple line in the append_to_quickfix function in quickfix.lua can solve this problem:
```
local function append_to_quickfix(error, data)
  local line = error and error or data

  line = vim.fn.iconv(line, "cp936", "utf-8") -- this line

  vim.fn.setqflist({}, "a", { lines = { line } })
  -- scroll the quickfix buffer to bottom
  if quickfix.check_scroll() then
    quickfix.scroll_to_bottom()
  end
end
```

### **Describe alternatives you've considered**
Is it possible to provide a set of encoding conversion options or introduce an event similar to QuickFixCmdPost to assist users in addressing encoding issues?

### **Additional context**
I really like this plugin and hope that its functionality can be further improved.

**Comment by Civitasv** [comment]
I've added an option to choose the encoding for quickfix:

```lua
...
      quickfix = {
        show = "always", -- "always", "only_on_error"
        position = "belowright", -- "bottom", "top"
        size = 10,
        encoding = "utf-8", -- if encoding is not "utf-8", it will be converted to "utf-8" using `vim.fn.iconv`
      },
...
```

You should set `encoding` to "cp936".

**Comment by ck961018** [comment]
> I've added an option to choose the encoding for quickfix:
> 
> ```lua
> ...
>       quickfix = {
>         show = "always", -- "always", "only_on_error"
>         position = "belowright", -- "bottom", "top"
>         size = 10,
>         encoding = "utf-8", -- if encoding is not "utf-8", it will be converted to "utf-8" using `vim.fn.iconv`
>       },
> ...
> ```
> 
> You should set `encoding` to "cp936".

It works, thank you.
