### ISSUE TITLE
Option to have :CMakeRun not change the current build target?

### ISSUE THREAD

**Issue by hsetlik** [Civitasv/cmake-tools.nvim#175]
Hi,
First of all I really appreciate this project, I'm using it for audio plugin development where I have a plugin target which runs inside an audio plugin host executable. Right now building the plugin and launching the host to run it works like:
1. With the build target set to PLUGIN and the launch target set to HOST, run `:CMakeBuild` to build the plugin
2. Run `:CMakeRun` to launch the host

This works, but `:CMakeRun` causes the build target to be set to HOST, which I need to manually change back to PLUGIN before building and running again. I'd really like an option to have `:CMakeRun` leave the build target unchanged. Thanks!

**Comment by Civitasv** [comment]
It's default now.

**Comment by hsetlik** [comment]
Ok thank you- is it an option in the config? I just updated to the latest commit but doing `:CMakeRun` still changes the build target for me.

**Comment by Civitasv** [comment]
It works for me. Can you record your operation?

**Comment by hsetlik** [comment]
https://github.com/Civitasv/cmake-tools.nvim/assets/39610301/10f53c35-02e2-4fa3-90d6-56a2c71d1486

You can see the build target switch from "Electrum_VST3" to "AudioPluginHost" on the status line at the bottom when I run the command.

**Comment by Civitasv** [comment]
That's weird, are you sure that you've updated to the latest commit?

**Comment by hsetlik** [comment]
Oh my mistake, I updated without reloading the plugin in Lazy, it's working now.

**Comment by Civitasv** [comment]
Okay, closing it for now, feel free to open it if you still have this problem.
