### ISSUE TITLE
Changed behaviour: change of cmake kit doesn't change build folder name. ( doesn't copy patterns from global config ).

### ISSUE THREAD

**Issue by Gerodote** [Civitasv/cmake-tools.nvim#179]
**Bug description**

Changed behaviour with a last update:
 -  change of cmake kit doesn't change build folder.

**Steps to reproduce**

<details><summary>Minimal configuration</summary>
</details>

1. Set in global config for the plugin `  cmake_build_directory = "build/${kit}/${kitGenerator}/${variant:buildType}",  `
2. Before:
     - switch kit ( i.e. was gcc v13. now clang v16 )
     - new dir in build ( was `build/GCC ...v13//Debug/... `, + new folder `build/Clang ...v16//Debug/...` )
     - there's results with another kit in another folder ( i.e. in `build/Clang ...v16//Debug`)
3. Now:
     - switch kit
     - no new dir ( what's interesting it seems it saves path not in `~/.cache/cmake_tools_nvim/pathtoproject.lua`, because I can't explain why it saves the value no matter deleting session file in the mentioned folder)
     - yep, kit is changed, though build dir name is not ( using the same folder. i.e. continuing using gcc's build folder, instead of clang )

**Expected behavior**

One of the following:
 - document the behaviour
 - "return" behaviour.
 
 if return behaviour, there's maybe such solution:
  - by default, copy pattern from global config's `cmake_build_directory` to session's settings `build_options`
  - allow it to be expanded by all of this. (  It seems to work already ! )
  - maybe add capability of copying of the pattern ( if it existed before in the session settings `build_options` ) when `:CMakeSelectBuildDir`

**Screenshots**

**Environment**

- OS:  a linux with neovim v0.9.4 and LuaJIT 2.1.1700008891
- Desktop environment:  KDE
- Plugins commit hash:  6c248e1

**Additional context**
<!-- Add any other context about the problem here. --

**Comment by Civitasv** [comment]
See comment: https://github.com/Civitasv/cmake-tools.nvim/issues/176#issuecomment-1850058948

**Comment by Gerodote** [comment]
Hm... I didn't changed it, though, it seemed it didn't work. IDK why, and sorry for the misleading.

Maybe it's possible to put somehow pattern string when `:CMakeSelectBuildDir` ?
Now : 
![image](https://github.com/Civitasv/cmake-tools.nvim/assets/58738099/c1c97ec9-304c-4cfb-b345-a9e32a774d78)

**Comment by Civitasv** [comment]
Interesting, It works for me.

https://github.com/Civitasv/cmake-tools.nvim/assets/37768049/5efb99c4-8446-4a63-b04d-62ec40862ccf

Can you record a video about your configuration and your operation?

**Comment by Civitasv** [comment]
Pushed a fix.

**Comment by Civitasv** [comment]
Closing for now, feel free to open it if you still have this problem.

**Comment by Gerodote** [comment]
It seems to work.  Thank you!
