### ISSUE TITLE
'bottom' is not a valid option for the quickfix position

### ISSUE THREAD

**Issue by minego** [Civitasv/cmake-tools.nvim#180]
**Bug description**
The example configuration commands and documentation show a number of options for the position of the quickfix window, including 'bottom' but that is not valid and causes confusing errors.

**Steps to reproduce**

Set the "position" option for quickfix to "bottom" and do any command that will trigger the quickfix window

**Expected behavior**

It should open the quickfix at the bottom as the name suggests

**Screenshots**

**Environment**

I've tested this on mac, linux and windows and got the same result on all 3

**Additional context**

The actual values that will work correctly are:
```
vertical
horizontal
leftabove
aboveleft
rightbelow
belowright
topleft
botright
```

There are also a number of combinations that would work properly. I suggest adding a note telling new users to run ':help vert' to see the neovim help on these commands

**Comment by Civitasv** [comment]
I've pushed a fix.

**Comment by minego** [comment]
Thank you!

I managed to figure it out, but it was confusing. I think that will help others.

**Comment by Civitasv** [comment]
Thanks!
