### ISSUE TITLE
Auto select target

### ISSUE THREAD

**Issue by minego** [Civitasv/cmake-tools.nvim#181]
If I run `CMakeBuild` it uses the last selected target. This makes sense, but I'd like to be able to automatically select a target either based on my current directory or based on the file I am editing.

**Comment by Civitasv** [comment]
That's not how cmake works. I don't think it is feasible.

**Comment by minego** [comment]
I may have to hack and see if I can make something work... I mean, you have a way to select a target and I know that cmake associates source files with their targets.

Basically I'd like to have a key binding that takes the path of the current buffer, then enumerates all the targets and checks to see if that file is associated with one, and then selects that target and rebuilds it.

I agree it probably isn't a simple task. I've been using Makefiles with cmake which works off the current directory, and I'm hoping to keep my workflow as close to that as I can while using your plugin to build so I can use any generator.

**Comment by minego** [comment]
I've been looking through your code trying to workout how to manage this, and I think I am starting to see how to make it work. I may try to create a PR for the feature.

In `config.lua` the `get_codemodel_targets` call loads a list of all the build targets. Each entry in that targets list includes a field named `directoryIndex` which can be used to find the directory where that target was created.

I think at this point that all I would need to change in the plugin to get the behavior I want would be to expose an API that takes a path, and tries to find a matching target.

So, for example, if the `targets` list included an entry like ```
{
   "directoryIndex": 3,
   "id": "libfoo::@abc123",
   "jsonfile": "target-libfoo-blahblah.json",
   "name":"libfoo",
   "projectIndex": 0
}
```

and `directories[3]` is an entry like ```
{
   "build": "lib/foo",
   "source": "lib/foo"
   ...
}
```

So, then I can add a hook in my config for changing the working directory, and when that happens make a call to look through those directories and find the one that is the best match, then look through the targets for one that references that directory, and that should give me the one I want to select.

I hope I'm making sense... Anyway, when I find some time I'll poke at this some more. I'm not sure when that will be, but hopefully soon.

**Comment by Civitasv** [comment]
Yes, it makes sense, it will be a very useful feature.

**Comment by Civitasv** [comment]
Actually, we have `CMakeShowTargetFiles` command, maybe that is helpful.

**Comment by Civitasv** [comment]
> This makes sense, but I'd like to be able to automatically select a target either based on my current directory or based on the file I am editing.

I've supported this.

- use `CMakeRunCurrentFile` to launch targets related to current file.
- use `CMakeBuildCurrentFile` to build targets related to current file.
- use `CMakeDebugCurrentFile` to debug targets related to current file.

Demo:

https://github.com/Civitasv/cmake-tools.nvim/assets/37768049/dcf04044-3c45-4068-b646-5967edc3dbc2

**Comment by minego** [comment]
That looks amazing! Thank you!

I'll try it out as soon as I can. This is really helpful. Thank you again!
