### ISSUE TITLE
Option to auto-close quickfix after a successful build

### ISSUE THREAD

**Issue by minego** [Civitasv/cmake-tools.nvim#186]
**Describe the problem or limitation you are having**
I like having the quickfix window automatically open while a build is running, and it is very useful to keep it open after a build failure but after a successful build I don't need to see it, and currently I have to switch to it and close it manually.

**Describe the solution you'd like**
I'd like an option to automatically close the quickfix window after a build completes successfully.

**Describe alternatives you've considered**

**Additional context**

**Comment by Civitasv** [comment]
You set quickfix.show to "only_on_error":
```lua
          quickfix = {
            ...
            show = "only_on_error",     -- "always", "only_on_error"
            ...
          },
```

**Comment by minego** [comment]
Yes, I'm aware of that option, but I prefer to see the output while it is building. Also, if you don't have the notifications enabled it becomes very hard to know if it is still running or not without seeing the output.

**Comment by minego** [comment]
That sounds perfect! I'll try it today. Thank you!

**Comment by minego** [comment]
Works perfectly! Thanks again!
