### ISSUE TITLE
Integrating CMake compilation errors with the Trouble plugin in NeoVim

### ISSUE THREAD

**Issue by Nullarity** [Civitasv/cmake-tools.nvim#190]
Hi,
I use the Trouble plugin for displaying LSP warnings and errors. Is it possible to integrate compilation errors into Trouble so that it will understand and display them? Currently, I have to use the quick list and Trouble simultaneously, which is quite inconvenient.

Thank you!

**Comment by Civitasv** [comment]
I believe that you can use `require("trouble").toggle("quickfix")`

**Comment by Nullarity** [comment]
Unfortunately, it doesn't work, Trouble doesn't see compilation errors. If I understand correctly, Trouble shows only LSP diagnostics, which is not always the case when we develop C++ applications. Maybe there is some other plugin I can use instead of Trouble?

**Comment by Civitasv** [comment]
I think you should see the ['errorformat'](https://neovim.io/doc/user/options.html#'errorformat') option of neovim.

**Comment by Nullarity** [comment]
Thank you, I will look into this. I'm quite new to neovim and am trying to understand how things should work here.
Just out of curiosity, if you program professionally in C++, what plugins do you use for diagnostics & compilation messages?
Thank you!

**Comment by Civitasv** [comment]
I use lsp, trouble.nvim and clangd_extensions. You can see my nvim config [here](https://github.com/Civitasv/runvim/tree/master).
