### ISSUE TITLE
Can support for floaterm？

### ISSUE THREAD

**Issue by yifan0414** [Civitasv/cmake-tools.nvim#194]
**Describe the problem or limitation you are having**

the floaterm is also a awesome plugin for neovim terminal.

the toggleterm
![image](https://github.com/Civitasv/cmake-tools.nvim/assets/45898625/ed40abb8-9e53-4f00-839c-fcb8b424b6c9)

the floaterm is more concise

![image](https://github.com/Civitasv/cmake-tools.nvim/assets/45898625/d80898f2-35eb-4d76-abaf-7be39a0edc29)

and floaterm can open multiple float terminal， More convenient multiplexing

[https://github.com/voldikss/vim-floaterm](url)

**Comment by Civitasv** [comment]
Maybe, I don't quite familiar with vimscript now. If you're, can you try to integrate it? You can define a new executor and runner easily, like `toggleterm.lua`.

**Comment by Civitasv** [comment]
<img width="660" alt="image" src="https://github.com/Civitasv/cmake-tools.nvim/assets/37768049/fc37d6ab-069f-4f58-931d-39e321c1099b">

I also make toggleterm better, use the latest commit.

**Comment by yifan0414** [comment]
Thanks for your reply, I am currently learning how to write plugins for Neovim, which might take some time. After I complete this runner for floaterm, I will submit a PR.
