### ISSUE TITLE
Run all tests with ctest

### ISSUE THREAD

**Issue by thar** [Civitasv/cmake-tools.nvim#195]
If I run CMakeRunTest it ask for a specific test to be executed.

I would like to be able to run all available tests with a command.

This can be achieved either by calling ctest without the '-R <regex>' option or by calling it with '-R ".*"'.

**Comment by khris190** [comment]
would be cool if we just got opt in cmake.run_test(opt) to be able to overwrite some stuff and that would let us just set "*" on filename to run all tests

**Comment by khris190** [comment]
option to run all was just merged, i'll try to update it for switch in lua if i find a good way of cleanly merging it with user_command arguments
![2024-04-24_18-15](https://github.com/Civitasv/cmake-tools.nvim/assets/29352561/efdac000-02f8-4be3-a940-1d9c8d092d93)

**Comment by Civitasv** [comment]
Closing for now, feel free to reopen it if you need further support.
