### ISSUE TITLE
Expected Lua number in scratch.lua:16

### ISSUE THREAD

**Issue by allenfrostline** [Civitasv/cmake-tools.nvim#197]
**Bug description**

The following error occurs for basically commands.

```
Error executing Lua callback: ...ck/lazy/opt/cmake-tools.nvim/lua/cmake-tools/scratch.lua:16: Expected Lua number
stack traceback:
        [C]: in function 'nvim_buf_set_lines'
        ...ck/lazy/opt/cmake-tools.nvim/lua/cmake-tools/scratch.lua:16: in function 'append'
        ...pack/lazy/opt/cmake-tools.nvim/lua/cmake-tools/utils.lua:237: in function <...pack/lazy/opt/cmake-tools.nvim/
lua/cmake-tools/utils.lua:220>
```

**Steps to reproduce**

- neovim version: 0.9.5
- cmake-tools.nvim commit: 055d7bb
- open a C++ project with CMakeLists.txt
- run `:CMakeGenerate!`

**Expected behavior**

Generate the specified build system.

**Comment by sleaper** [comment]
Same issue:

NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794

```
Error executing Lua callback: ...e/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/scratch.lua:16: Expected Lua number                                     
stack traceback:                                                                                                                                      
        [C]: in function 'nvim_buf_set_lines'                                                                                                         
        ...e/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/scratch.lua:16: in function 'append'                                                          
        ...are/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/utils.lua:237: in function <...are/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/utils.lua:220>
```

**Comment by Civitasv** [comment]
I'm also at Nvim v0.9.5, and it works fine. Can you share the content of *cmake-tools* buffer?

**Comment by sleaper** [comment]
> I'm also at Nvim v0.9.5, and it works fine. Can you share the content of *cmake-tools* buffer?

What/Where is cmake-tools buffer?

**Comment by Civitasv** [comment]
This \*cmake-tools\* buffer.
<img width="722" alt="SCR-20240211-opgi" src="https://github.com/Civitasv/cmake-tools.nvim/assets/37768049/abe6f713-b8f1-4cf7-8a4d-cd7a8a7db217">

**Comment by sleaper** [comment]
> This *cmake-tools* buffer. <img alt="SCR-20240211-opgi" width="722" src="https://private-user-images.githubusercontent.com/37768049/303907195-abe6f713-b8f1-4cf7-8a4d-cd7a8a7db217.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NDI4MjIsIm5iZiI6MTcwNzY0MjUyMiwicGF0aCI6Ii8zNzc2ODA0OS8zMDM5MDcxOTUtYWJlNmY3MTMtYjhmMS00Y2Y3LThhNGQtY2Q3YThhN2RiMjE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDA5MDg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlNTQ5ZjZmNTBiNzgwOWMyYzAzMDQzNmFkYjI4Y2RmNTZhNmMyN2RkYjJmMjI4NThhYTQyNGU4ZjU5Njc4NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.793s24N2Gg9WKvl8JuMM4i17TVBmdnyZ_yA3gtFKSN4">

![image](https://github.com/Civitasv/cmake-tools.nvim/assets/19505081/93dc377f-b585-4db4-a916-04978b68734e)

When I open cpp file, I have only this buffer.

**Comment by Civitasv** [comment]
Do you check if the root dir contains CMakeLists.txt file?

**Comment by sleaper** [comment]
Yes it does. 
![image](https://github.com/Civitasv/cmake-tools.nvim/assets/19505081/7c2860ee-00c0-404a-8d6d-0cb3d8fe3e0d)

**Comment by Civitasv** [comment]
Do you invoke the setup function?

**Comment by sleaper** [comment]
> Do you invoke the setup function?

Oh, of course I did not. Thanks man. Sorry for wasting your time.

**Comment by Civitasv** [comment]
That’s alright.😀

**Comment by allenfrostline** [comment]
@Civitasv Thanks man! Was omitting the explicit setup function too. Closing this issue now.
