### ISSUE TITLE
The *cmake-tools* buffer clutters the tab list and breaks the plugin when closed

### ISSUE THREAD

**Issue by cjuub** [Civitasv/cmake-tools.nvim#198]
**Bug description**
Recent introduction of \*cmake-tools\* buffer makes this buffer always be created when opening a project. If this buffer is deleted then the commands in this plugin stop working. Furthermore, it clutters the tab list of open files, as I try to keep the tab list clean with only the files I'm currently working on.

This is a problem with common operations like "delete all buffers except current one" or "delete all buffers except the pinned ones", which will delete \*cmake-tools\* buffer, causing the plugin commands to break.

Making the buffer unlisted with something like this works (not listed in tabs, won't be deleted by tab close operations):
`vim.api.nvim_buf_set_option(buf, "buflisted", false)`

But I'm having issues getting an autocmd run this, and I rather not do it manually. **In my opinion it would be better if the plugin does not automatically show this buffer as listed in tab list.** Maybe store the information in a file instead that can be used when debugging/posting an Issue?

**Steps to reproduce**

<details><summary>Minimal configuration</summary>
Delete the \*cmake-tools\* buffer and then run e.g. cmake configure or build commands
</details>

**Expected behavior**
No extra buffer that clutters the tab list and that can't be deleted.

**Environment**

- OS: Arch Linux with LazyVim
- Desktop environment: sway
- Plugins commit hash: 8e4e7f28652b53d90324703765a0827a95caa4e2

**Contents in the \*cmake-tools\* buffer**

:D

**Comment by athanase** [comment]
I agree with this issue, but having a way to read previous commands to debug for example is a nice feature.
Would it be better to keep a list of previous commands and expose an API to the user ?

**Comment by Civitasv** [comment]
> vim.api.nvim_buf_set_option(buf, "buflisted", false)

I agree with this.

**Comment by cjuub** [comment]
That works! Thank you Civitasv, for the fix and just in general for this plugin.
