### ISSUE TITLE
Execute the command, and a pop-up window will appear to manually select the target. If no selection is made and the pop-up window disappears, the command will no longer bring up the corresponding pop-up window.

### ISSUE THREAD

**Issue by serendipitywgy** [Civitasv/cmake-tools.nvim#200]
Please view the video demonstration. Once you click on the window with the mouse to make it disappear, you can no longer use commands to bring up the pop-up window.

https://github.com/Civitasv/cmake-tools.nvim/assets/68495280/20386524-434d-4a52-af46-bfc3f0e40a86

**Comment by Civitasv** [comment]
Which pop-up window do you use?

**Comment by serendipitywgy** [comment]
Actually, I don't know which pop-up window plug-in it is, I use the default configuration of lazyvim. After I checked the official website of lazyvim, the official default configuration is as follows

![image](https://github.com/Civitasv/cmake-tools.nvim/assets/68495280/0fdea98a-9fb7-4408-b4e8-738349bda092)
![image](https://github.com/Civitasv/cmake-tools.nvim/assets/68495280/025147c5-056d-4cb4-ae81-c029253fd2a2)

**Comment by Civitasv** [comment]
This plugin just uses `vim.ui.select` to select the avaliable options, by default, it shows like:
<img width="615" alt="image" src="https://github.com/Civitasv/cmake-tools.nvim/assets/37768049/6146eb00-4607-4fe0-acd3-0377eba1e5a8">


So you should check which plugin shows this pop window, and debug it.

**Comment by serendipitywgy** [comment]
Okay, thank you for your reply, I will research it further.

**Comment by Civitasv** [comment]
Closing it for now. Feel free to open it if you need further support.
