### ISSUE TITLE
How to get current cmake args in neovim's lua?

### ISSUE THREAD

**Issue by Gerodote** [Civitasv/cmake-tools.nvim#203]
**Describe the problem or limitation you are having**

I try to use new feature of cmake: debugger of CMakeLists.txt .

I got it working somehow: [here's the problem line](https://github.com/Gerodote/Nvchad_config_cpp/blob/016d0d0949b952ef7db08907a41afa403c86aa82/configs/cmake.lua#L84)

As you can see, it adds some params like `--log-level DEBUG` and so on.

The problem is next: I genuinely don't know how to get cmake args cmake-tools.nvim adds to cmake generate command. That's why I wrote some stuff there, and I don't know how to give it args from `:CMakeSettings` -> return -> generate_options.
I see [this doc](https://github.com/Civitasv/cmake-tools.nvim/blob/master/docs/howto.md#mimic-ui-of-cmake-tools-toolbar-in-visual-studio-code) and maybe there's no such "getter" function.

**Describe the solution you'd like**

- a. Explain how to get it in lua, because I'm really new to writing something by myself using lua
- b. Add a getter for this or for some or for all relevant values from `:CMakeSettings`

**Describe alternatives you've considered**

Right now live with default generate options that are there.

**Additional context**
<!-- Add any other context or screenshots about the feature request here. --

**Comment by Civitasv** [comment]
We utilize `dap.run` to support debug for targets(executable): https://github.com/Civitasv/cmake-tools.nvim/blob/eb798c899bf78996e835188d7bb9d9d4a3066d01/lua/cmake-tools/init.lua#L1375.
To implement debuggers for cmake, I think you should add a new function to init.lua, inside this function, configure dap adapters for cmake, and start debugging session:

```lua
function cmake.debug_cmake_file()
  ...
  dap.adapters.cmake = function(callback, config)
    callback {
      type = "pipe",
      pipe = "${pipe}",
      executable = {
        command = const.cmake_command,
        args = { "--debugger", "--debugger-pipe=${pipe}", tostring(cmake_tools.get_build_directory()), "--log-level DEBUG", "-DFETCHCONTENT_QUIET=OFF"},
      },
    }
  end
  ...
end
```

**Comment by Civitasv** [comment]
You can use `cmake.get_generate_options()` to get the generate options.

**Comment by Gerodote** [comment]
Yep, it works! Thanks.

Could you add this somewhere to docs, please?

**Comment by Civitasv** [comment]
Added. See [howto](https://github.com/Civitasv/cmake-tools.nvim/blob/master/docs/howto.md#mimic-ui-of-cmake-tools-toolbar-in-visual-studio-code)
