### ISSUE TITLE
Command: CMakeStopRunner not working when using toggleterm.

### ISSUE THREAD

**Issue by n-cho** [Civitasv/cmake-tools.nvim#206]
**Bug description**

CMakeStopRunner does not kill the process when using toggleterm as runner & executor.

**Steps to reproduce**

1. Set `cmake_executor = { name = "toggleterm" }` and `cmake_runner = { name = "toggleterm" }` in `opts`
2. Generate CMake project with the following `CMakeLists.txt` and a blank `main.cpp` file.
```
cmake_minimum_required(VERSION 3.13)
project(TESTPROJECT)
set(CMAKE_CXX_STANDARD 14)

set(SOURCE_FILES main.cpp)

add_executable(TESTPROJECT ${SOURCE_FILES})
```
3. Run a program in `main.cpp` that doesn't end automatically. For example ...
```
#include <iostream>;

int main() {
  char s[] = "";
  std::cin >> s;
  return 0;
}
```
4. Try to use `CMakeStopRunner` to kill the process before it finishes.

<details>
<summary>Minimal configuration</summary>

- Use NvChad v2.5.
- Install `toggleterm` and `cmake-tools` using `lazy.nvim`.

</details>

**Expected behavior**

The command does not kill the process. 

**Screenshots**

<img width="1440" alt="screenshot0" src="https://github.com/Civitasv/cmake-tools.nvim/assets/59635961/b9c33442-0349-4caf-9af7-5045c757752b">
<img width="1440" alt="screenshot1" src="https://github.com/Civitasv/cmake-tools.nvim/assets/59635961/ee969e08-c367-45b7-8a12-43ee23973b8c">
<img width="1440" alt="screenshot2" src="https://github.com/Civitasv/cmake-tools.nvim/assets/59635961/275e836f-d33e-4f65-8df2-f8ca5a1b8d38">

**Environment**

- OS: macOS Sonoma v14.3.1 
- Desktop environment: 
- Plugins commit hash: 

**Contents in the \*cmake-tools\* buffer**

**Comment by Civitasv** [comment]
Use the latest commit, I've fixed it.
