### ISSUE TITLE
Support flexible build directory naming & structure for enabling multiple build types

### ISSUE THREAD

**Issue by krishnakumarg1984** [Civitasv/cmake-tools.nvim#21]
Currently, the build directory name needs to be hard coded in the configuration. It would be helpful to have a more flexible approach wherein a `build_dir_prefix` strings is provided to be user configurable. This will enable C++ developers to have access to multiple type of builds.

Examples:
- `build_dir_prefix`: **`cmake_build_`**
In the above example, the build directory will become `cmake_build_Debug`, `cmake_build_Release`, wherein the appropriate suffix is chosen by the build type

- `build_dir_prefix`: **`build/`**
In this above example with the trailing `/`, a classical nested hierarchical structure of various types of builds can be facilitated
```
build
├── Debug
├── MinRelease
├── Release
└── RelwithDebInfo
```

The above is a classical build tree for multiple type of builds, and is easily done through cmake invocations at the command-line, but this is not currently possible with this plugin.
The vimscript plugin, `[cmake4vim](https://github.com/ilyachur/cmake4vim)` already supports this, and I am using it now in my projects, but I'd like to move to this lua-based plugin, mainly for its integration with `nvim-dap`.

Of course, to prevent breaking changes to existing users' configurations, the `build_dir_prefix` behaviour should be activated only when `cmake_build_directory` is set explicitly to an empty string. Otherwise, we simply ignore the `build_dir_prefix` setting, and simply overwrite builds each time to the folder configured in `cmake_build_directory` (the current behaviour).

**Comment by Civitasv** [comment]
Thanks for your suggestion. I will implement this option soon.

**Comment by Civitasv** [comment]
Hi, please see the latest commit. I've implemented this feature.

```lua
require("cmake-tools").setup({
...
  cmake_build_directory = "",
  cmake_build_directory_prefix = "build/",
...
})
```
