### ISSUE TITLE
Symlink compile_commands.json doesn't appear to work on windows

### ISSUE THREAD

**Issue by natecheadle** [Civitasv/cmake-tools.nvim#213]
**Bug description**
compile_commands.json is not being symlinked to the root directory of the source folder on windows. 

Running the same command that is being passed to vim.cmd works properly from the same CLI environment. 
cmake -E create_symlink {source} {destination}

This works fine on OSX. 

(I did not test my project on Linux)

**Steps to reproduce**
clone https://github.com/natecheadle/CppTemplate
mkdir out/Debug
nvim .
:CMakeGenerate

**Expected behavior**
expected compile_commands.json to be symlinked in the root source directory

**Environment**

- OS: Windows
- Plugins commit hash: a4cd0b3a2c8a166a54b36bc00579954426748959
- CLI: Launched from Powershell

**Work Around**
I was able to work around this issue by adding the following to my main CMakeLists.txt and disabling the symlink feature in this plugin. (This does exactly what this plugin is trying to do as far as I can tell)

```
execute_process(
    COMMAND ${CMAKE_COMMAND} -E create_symlink  
    ${CMAKE_BINARY_DIR}/compile_commands.json  
    ${CMAKE_SOURCE_DIR}/compile_commands.json  
)
```

**Comment by khris190** [comment]
what do You get when you execute `print(vim.loop.cwd())` it might be an error with that, it should be your ${CMAKE_SOURCE_DIR}

**Comment by natecheadle** [comment]
`:lua print(vim.loop.cwd())` returns my {CMAKE_SOURCE_DIR}. 

This is a different windows PC than what I originally reported the issue but it does still fail. On my other PC showing the issue it was a silent failure, now it does report an error in the function trying to symlink the file. The commit of CMake-Tools that I am using on this PC does look to be different though (8506c426d5b361dbaa7c61c0490a2589a9c555ce).

The following error is what I receive. 

```
eposIgnosiGameEngine.out^HuildMSVCRelease/compile_commands.json C:Usersec2(): Vim:E492: Not an editor command: atecsource
eposIgnosiGameEngine/compile_commands.json                                                                                                                              stack traceback:
        [C]: in function 'nvim_exec2'
        vim/_editor.lua:341: in function 'cmd'
        ...vim-data/lazy/cmake-tools.nvim/lua/cmake-tools/utils.lua:90: in function 'softlink'
        ...nvim-data/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:1426: in function 'compile_commands_from_soft_link'                                                         ...nvim-data/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:1413: in function 'configure_compile_commands'                                                              ...nvim-data/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:176: in function 'on_success'                                                                               ...vim-data/lazy/cmake-tools.nvim/lua/cmake-tools/utils.lua:256: in function 'on_exit'                                                                                  ...-data/lazy/cmake-tools.nvim/lua/cmake-tools/quickfix.lua:90: in function 'cb'
        vim/_editor.lua:263: in function <vim/_editor.lua:262>
```

The first line looks to be a mangled path to my CMAKE_BINARY_DIR and my CMAKE_SOURCE_DIR

**Comment by khris190** [comment]
do You perhaps have a space in the filepath? if yes i see how it could have happened and i'll deal with that

**Comment by khris190** [comment]
If the space character in path was the problem i created a pull request fixing that, not really a windows error it seems.

**Comment by khris190** [comment]
oh, i didn't know  mentioning links it like that

**Comment by khris190** [comment]
@natecheadle did the last commit fix your issue?

**Comment by natecheadle** [comment]
Thank you. It does appear to be working. Not sure if this is intended behavior, but it does prompt me to run the command and I have to hit enter after the generate step.

```
:!cmake -E create_symlink C:\repos\CppTemplate\out/Debug/compile_commands.json C:\repos\CppTemplate/compile_commands.json

Press ENTER or type command to continue
```

A note for other windows users, and something I missed when creating a minimal example. It doesn't look like Visual studio generator creates a compile_commands.json file. This is the default generator for Windows in CMake, I normally use Ninja and specifying this as your generator does correctly create a compile_commands.json file.
