### ISSUE TITLE
quick start

### ISSUE THREAD

**Issue by rgzntrade** [Civitasv/cmake-tools.nvim#216]
vscode has quick start.
Can you support it?

**Comment by khris190** [comment]
are You talking, 1 to 1 replication?

**Comment by rgzntrade** [comment]
> are You talking, 1 to 1 replication?

Copying vscode's quick start is certainly nice, the minimum expectation is something like neovim-cmake. Except that neovim-cmake is buggy and doesn't change the project name.

**Comment by khris190** [comment]
it can be done

**Comment by rgzntrade** [comment]
> 这是可以做到的，我会尽力在本周末之前处理它

Thank you very much
