### ISSUE TITLE
Question about CMakeLists

### ISSUE THREAD

**Issue by attixt** [Civitasv/cmake-tools.nvim#22]
Hello, thank you for making this plugin! I am sure this is a super basic question, but I am very new to using VIM so please forgive me lol. I followed the instructions in the ReadMe, but I end up getting this error when I try to run CMake commands: " Cannot find CMakeLists.txt at cwd. Are we supposed to create the CMake files manually? Sorry again for the extremely basic question.

**Comment by Civitasv** [comment]
Yes, you should create the CMake files manually, a typical file structure will be like follow image:
![image](https://user-images.githubusercontent.com/37768049/206403491-2c50eea6-2ba4-464b-8682-da536e45cb43.png)
