### ISSUE TITLE
`CMakeBuild` argument passed to cmake before `--build` not after

### ISSUE THREAD

**Issue by meuter** [Civitasv/cmake-tools.nvim#23]
**Bug description**

when you call `:CMakeBuild -j32`, the plugin invokes cmake as `cmake -j12 --build ...` which results in cmake erroring out. If you put `-j12` in `config.build_options`, the flags are appended at the end of the line and it works as expected though.

**Steps to reproduce**

in any cmake project, clean the build directory, open neovim and run `:CMakeBuild j32`.

**Expected behavior**

I would expect the arguments of CMakeBuild to be passed after the `--build` flag. So in my example, cmake would be called as `cmake --build -j32 ...`.

**Environment**

- OS: Ubuntu 20.04
- Desktop environment:  none - ssh'ed into a remote server
- Plugins commit hash: 86124bddb5638368985c0b59b7c134e499a9e21b

**Additional context**

This seems to be where the argument order is mixed up: https://github.com/Civitasv/cmake-tools.nvim/blob/master/lua/cmake-tools/init.lua#L193

Thanks for an awesome plugin BTW!

**Comment by Civitasv** [comment]
Sorry for my late! Plz see commit 1b1c19bcc77bb569cc24373ffbf444a2ba765372, it should work now.

**Comment by meuter** [comment]
Thanks ! Sorry for the late reply, I was away from work last week. I'll test it out tomorrow and let you know.
