### ISSUE TITLE
Support fish shell

### ISSUE THREAD

**Issue by dragove** [Civitasv/cmake-tools.nvim#232]
**Describe the problem or limitation you are having**

When using fish shell, `$0` is not the variable for exit code, it should be `$status`

**Describe the solution you'd like**

following code is working but I'm not familiar with lua and this code is ugly.

```lua
local shell = vim.env.SHELL
local exit_op = nil
if shell and shell:sub(-#"fish") == "fish" then
  exit_op = "$status"
else
  exit_op = "$0"
end

local get_command_handling_on_exit = function()
  return "echo "..exit_op.." > "
    .. get_last_exit_code_file_path() -- write exitcode to file
    .. " && rm "
    .. get_lock_file_path() -- remove lock file
end
```

**Comment by Civitasv** [comment]
Thanks, I've supported this. Use the latest commit.

**Comment by dragove** [comment]
There is still something not working. I left comment here. https://github.com/Civitasv/cmake-tools.nvim/commit/72a5c1b52b32682b7b6b3fb62faa982868602ffb#r142880100

**Comment by Civitasv** [comment]
Updated.

**Comment by dragove** [comment]
Lots of thanks! now, `CMakeRun` works great on fish.
