### ISSUE TITLE
Slowdown every time cursor is moved

### ISSUE THREAD

**Issue by cjuub** [Civitasv/cmake-tools.nvim#237]
**Bug description**
As of commit adfac36301d14105e5dbd4971e2168edc5831335, I experience heavy slowdown whenever the cursor is moved. **It only becomes noticeable in larger projects.**

It is very difficult to navigate e.g. by holding down hjkl keys. As everything just freezes until I let go and then the cursor has jumped a long way. It affects everything, from buffer, to terminal integration and tree navigation.

Looking at the diff in the commit this started, the autocmd looks like the culprit **(though I have not verified that)**:
```
vim.api.nvim_create_autocmd({ "CursorMoved", "CursorMovedI" }
```

Perhaps the logic handled by this auto command is too heavy to run on each cursor movement for larger projects.

**Steps to reproduce**

<details><summary>Minimal configuration</summary>
Not provided. I don't believe it matters in this case. But it's just simple setup with nothing weird going on.

Can provide it if requested.
</details>

**Expected behavior**

When moving the cursor, mainly holding down hjkl keys, the cursor should not freeze in place due to heavy load. 

**Screenshots**

**Environment**

- OS:  WSL
- Desktop environment: 
- Plugins commit hash:  adfac36301d14105e5dbd4971e2168edc5831335

**Contents in the \*cmake-tools\* buffer**

Don't have it available as of creating this PR, problematic large projects are on my work computer. Can provide if requested.

**Comment by deeedob** [comment]
Indeed, facing the same problem and disabled `cmake_virtual_text_support`. We iterate through all sources in that autocmd on every cursor move? Seems extremely heave to me for a cursor move event.

**Comment by Civitasv** [comment]
Use the latest commit, see if it helps.

**Comment by cjuub** [comment]
Yes it does, much better. Thank you.
