### ISSUE TITLE
Whitespace makes CMakeGenerate error

### ISSUE THREAD

**Issue by Erland366** [Civitasv/cmake-tools.nvim#238]
**Bug description**
During `:CMakeGenerate", if the directory name has a whitespace in it, it will generate unwanted behavior. 

In my setup, it will create a quotes directory and a semicolon directory. 

For example, let's say my current directory name is "nvim test". The generated file will be : 

`/home/Cpp_projects/nvim test/"/home/Cpp_projects/nvim test/out/Debug"/...`

and 

`/home/Cpp_projects/nvim test/;/home/Cpp_projects/nvim;test/out/Debug"/...`

Note that both the double quotes is causing the error. I tried using paths without space and `:CMakeGenerate` is working as usual

**Steps to reproduce**
- create a directory with a whitespace on it, ex : `nvim test`
- Run `:CMakeQuickStart` with arbitrary project name to create `CMakeLists.txt`
- Run `:CMakeGenerate` to get the error

**Expected behavior**
My expected behavior is to plugin to successfuly run `:CMakeGenerate` and generate `compile_commands.json` and `out/` directory

**Screenshots**
![image](https://github.com/Civitasv/cmake-tools.nvim/assets/68678137/56b63586-0d28-42c5-9693-30b865c3aedf)

**Environment**

- OS: Ubuntu
- Desktop environment: Gnome
- Plugins commit hash: 131540d (CMIIW)

**Comment by Civitasv** [comment]
Which executor are you using?

**Comment by Civitasv** [comment]
Use the latest commit, I've fixed this.

**Comment by Erland366** [comment]
Sorry for the very late reply, I am not sure about what you mean by executor (I am new with C or Cpp) but if you mean compiler, then I am using gcc/g++.

Btw I can confirm that this is now working with the latest commit. Thank you so much for the help!
