### ISSUE TITLE
Presets are not ignored when `cmake_use_preset` is set to false

### ISSUE THREAD

**Issue by sillydan1** [Civitasv/cmake-tools.nvim#242]
**Bug description**

We are using presets files with test and package presets, and this plugin doesn't support those, so I want to disable the feature, as it doesn't necessarily matter for me during development. However, I still get an error whenever I try to load the project:

```
E5108: Error executing lua: vim/_editor.lua:0: nvim_exec2(): Vim:Error executing Lua callback: ...e/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/presets.lua:238: attempt to index local 'preset' (a nil value)
stack traceback:
        ...e/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/presets.lua:238: in function 'get_build_dir'
        ...hare/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:98: in function <...hare/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:61>
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        /home/agj/.config/nvim/init.lua:574: in function </home/agj/.config/nvim/init.lua:574>
stack traceback:
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        /home/agj/.config/nvim/init.lua:574: in function </home/agj/.config/nvim/init.lua:574>
```

<details><summary>Minimal configuration</summary>
My lua configration

```lua
require('cmake-tools').setup{
  cmake_use_preset = false, -- we use very new cmake features
}
```

</details>

**Environment**

- OS: Ubuntu 24.04 LTS
- Plugins commit hash: 09bd614

**Comment by sillydan1** [comment]
So far, I've just manually disabled the section where it loads the presets file and it seems to sidestep the problem:

```diff
diff --git a/lua/cmake-tools/init.lua b/lua/cmake-tools/init.lua
index 3151edc..cfbaff2 100644
--- a/lua/cmake-tools/init.lua
+++ b/lua/cmake-tools/init.lua
@@ -83,7 +83,7 @@ function cmake.generate(opt, callback)
   -- if exists presets, preset include all info that cmake
   -- needed to execute, so we don't use cmake-kits.json and
   -- cmake-variants.[json|yaml] event they exist.
-  local presets_file = config.base_settings.use_preset and presets.check(config.cwd)
+  local presets_file = false and config.base_settings.use_preset and presets.check(config.cwd)
   if presets_file and not config.configure_preset then
     -- this will also set value for build type from preset.
     -- default to be "Debug"
```

The `config.base_settings.use_preset` is set to `false` when configuring, but for some reason when I invoke the plugin then it is set to `true` again.

**Comment by Civitasv** [comment]
You should specify `cmake_use_preset` to true when you need presets.

**Comment by sillydan1** [comment]
> You should specify `cmake_use_preset` to true when you need presets.

As I said:

> I want to disable the feature, as it doesn't necessarily matter for me during development.

I dont want the plugin to load the file at all. I only use the presets file during CI. The issue is that when I set `cmake_use_preset` to `false`, it still tries to use the presets file.

**Comment by Civitasv** [comment]
You can use `CMakeSettings` to open local settings about your project. Then set `use_preset` to false.

**Comment by sillydan1** [comment]
Did not know about `:CMakeSettings` :smile: The readme has no mention of `:CMakeSettings`, maybe it should? 

Closing as this solves my problem :+1: thanks!
