### ISSUE TITLE
Automatic split size?

### ISSUE THREAD

**Issue by TheComet** [Civitasv/cmake-tools.nvim#247]
**Describe the problem or limitation you are having**
If I manually resize the terminal split, running ```:CMakeRun``` will resize it back to whatever ```split_size``` is set to.

**Describe the solution you'd like**
I'd like a way to configure cmake-tools to not resize my terminal window and use whatever it is currently set to.

**Comment by lceWolf** [comment]
proposal implemented in #253

**Comment by lceWolf** [comment]
implementation merged. Issue can be closed
