### ISSUE TITLE
build_options containing '--' should be appended at the end

### ISSUE THREAD

**Issue by obhi-d** [Civitasv/cmake-tools.nvim#261]
If you try to pass an option like `'--', '-k', '0'`, it gets 
placed before --target, causing target to be passed to Ninja generator.

**Comment by Ryex** [comment]
also an issue when using it with a VisualStudio generator and you want to pass `{ "--", "/p:UseMultiToolTask=true", "/p:EnforceProcessCountAcrossBuilds=true"}` to get parallel builds

**Comment by Civitasv** [comment]
Should be resolved by #263
