### ISSUE TITLE
How to select target with telescope plugin？

### ISSUE THREAD

**Issue by SonglinLife** [Civitasv/cmake-tools.nvim#27]
Hi, I want to use the telescope plugin to select build target and type, just like your video. but I can't find any hints in readme.
![image](https://user-images.githubusercontent.com/61929733/212233910-0450bf38-c82a-43ff-ab10-b7015f6a75e4.png)

**Comment by Civitasv** [comment]
I use [telescope-ui-select](https://github.com/nvim-telescope/telescope-ui-select.nvim) to achieve that. And I've added a section about how I configure this. See https://github.com/Civitasv/cmake-tools.nvim#how-to-make-cmake-tools-work-exactly-like-it-in-exmaple-video.

**Comment by SonglinLife** [comment]
thanks for your reply, I am stupid 😭
