### ISSUE TITLE
Regression from PR 255 - Can No Longer Select Preset on Windows

### ISSUE THREAD

**Issue by natecheadle** [Civitasv/cmake-tools.nvim#274]
**Bug description**
Since PR #255 with the refactoring of presets I cannot longer select a preset to use for the generate step. When I run CMakeSelectConfigurePreset the list is empty. When I checkout the commit prior to this pr everything works as it previously did. 

This appears to affect both CMakeUserPresets and CMakePresets (no user presets)

Everything seems to work properly in a Linux environment

**Steps to reproduce**
1. clone https://github.com/natecheadle/CMakeCPPTemplate into a short path like D:\repos\
2. open nvim in a x64 window developer power shell 
3. Execute CMakeSelectConfigurePreset
4. The list is empty and nothing can be selected

**Environment**

- OS: Windows
- Plugins commit hash: 53bc526

** Work-around **
Checkout e169948 and use that commit instead. (There is a separate bug that has since been fixed so can't use the commit exactly prior to the presets refactoring)

**Comment by lceWolf** [comment]
should be fixed with https://github.com/Civitasv/cmake-tools.nvim/pull/272

**Comment by pcorbineau** [comment]
Got similar issue on last master commit.
still got redudant log on https://github.com/Civitasv/cmake-tools.nvim/commit/e16994847af7e630e2568621aae0f28537a6952c
`|| Unknown argument -DCMAKE_EXPORT_COMPILE_COMMANDS=1`
But at least it compiles.

**Comment by pcorbineau** [comment]
I confirm https://github.com/Civitasv/cmake-tools.nvim/pull/272 fix build issue.
Someone know why I got redundant log :
`|| Unknown argument -DCMAKE_EXPORT_COMPILE_COMMANDS=1`
on CMakeBuild

for info here is my config : 
```lua
    opts = {
        cmake_regenerate_on_save = false,   -- auto generate when save CMakeLists.txt
        cmake_virtual_text_support = false, -- Show the target related to current file using virtual text (at right corner)
    },

```

**Comment by natecheadle** [comment]
I will confirm #272 fixes my issue on Monday. Thanks for investigating and providing a fix.

**Comment by natecheadle** [comment]
I can confirm that merging the change from #272 would resolve this
