### ISSUE TITLE
wrong folder warning for lua_ls when opening setting with CMakeSettings

### ISSUE THREAD

**Issue by cxwx** [Civitasv/cmake-tools.nvim#280]
**Bug description**

wrong folder warning for lua_ls when opening setting with CMakeSettings
```
   Warn  13:53:31 lsp.message LSP Message (lua_ls) More than 100000 files have been scanned. The current scanned directory is `/Users/chenxu/software`. Please see the [FAQ](https://luals.github.io/wiki/faq/#how-can-i-improve-startup-speeds) to see how you can include fewer files. It is also possible that your [configuration is incorrect](https://luals.github.io/wiki/faq#why-is-the-server-scanning-the-wrong-folder).

```
**St
<img width="1400" alt="截屏2024-11-28 13 58 00" src="https://github.com/user-attachments/assets/d5bc5999-2ddf-4e82-8567-ef56a7eb5cb1">
eps to reproduce**

<details><summary>Minimal configuration</summary>
- plugin cmake-tools
- plugin nvim-lsp
- using lua_ls lsp

</details>

I
`CMakeSettings`

**Expected behavior**

**Screenshots**

**Environment**

- OS: 
- Desktop environment: 
- Plugins commit hash: 

**Contents in the \*cmake-tools\* buffer**

**Comment by Civitasv** [comment]
I think you can fix this error by change configuration of lua_ls instead of this plugin.
