### ISSUE TITLE
Reopen output window after CMakeRun

### ISSUE THREAD

**Issue by deveezy** [Civitasv/cmake-tools.nvim#29]
After CMakeRun i see output on the bottom of output, but if i moved to "code window" my output closed.

**Bug description:**

I can escape from terminal mode in output window and then move to code window. But often i need to get rid of window for a while, write some code, and then return to it. 

**Expected behavior:**
Toggle output window keymap

**BTW**
Thanks for an awesome plugin especially after 2 years vscode experience

**Comment by Civitasv** [comment]
You can use `<C-\><C-n>` to change neovim's mode from terminal to normal, then you can move to and from your code window.

For launching targets,  this plugin uses `term` command, and after launching, this process is end, then if you press any key, the terminal will be closed. Currently, I don't find a way to execute targets in terminal, and reuse this terminal, like it in vscode. If you have any suggestions, please let me know.
