### ISSUE TITLE
configuration not work

### ISSUE THREAD

**Issue by lizhuoran1019** [Civitasv/cmake-tools.nvim#3]
Hi, this plugin is very useful for me, but I want to change debug to cppdbg, however my configuration is not working.
When I use :CMakeDebug, it still calls codelldb.Then I tried to change other configurations, but it still did not work.
![image](https://user-images.githubusercontent.com/43104914/198870720-cddc337c-6ec1-4cc5-aff8-4606f3f60cd8.png)
Here is my configuration code:
``` lua
-- plugins.lua
use({
  "Civitasv/cmake-tools.nvim",
  config = function()
    require("plugin-config.cmake-tools")
  end,
})
```

``` lua
-- plugin-config/cmake-tools.lua
local status, cmake = pcall(require, "cmake-tools")
if not status then
  vim.notify("没有找到 cmake-tools")
  return
end

cmake.setup({
  cmake_command = "cmake",
  cmake_build_directory = "build",
  cmake_build_type = "Debug",
  cmake_generate_options = { "-D", "CMAKE_EXPORT_COMPILE_COMMANDS=1" },
  cmake_build_options = {},
  cmake_console_size = 10, -- cmake output window height
  cmake_show_console = "always", -- "always", "only_on_error"
  cmake_dap_configuration = { name = "Launch file", type = "cppdbg", request = "launch" }, -- dap configuration, optional
  cmake_dap_open_command = require("dap").repl.open, -- optional
})
```

**Comment by Civitasv** [comment]
Hi, @lizhuoran1019, this error message means that you don't specify `dap.adapters.codelldb`. Which may not scope of cmake-tools.nvim.

**Comment by lizhuoran1019** [comment]
I changed the `cmake_dap_configuration` in the configuration file,like this:
`cmake_dap_configuration = { name = "Launch file", type = "cppdbg", request = "launch" },`
But it does not work, `:CMakeDebug` does not call cppdbg, but still calls codelldb

**Comment by lizhuoran1019** [comment]
I don't understand why my configuration is not working.

**Comment by Civitasv** [comment]
See my config for dap, it should work: [runvim](git@github.com:Civitasv/runvim.git)

**Comment by Civitasv** [comment]
But as long as you configure cppdbg adapter appropriately, at least it should not notify **undefined**.

**Comment by Civitasv** [comment]
Check the latest, now it should work.
