### ISSUE TITLE
Handle Preset include

### ISSUE THREAD

**Issue by CarlosNihelton** [Civitasv/cmake-tools.nvim#30]
**Describe the problem or limitation you are having**

`CMakePresets.json` and `CMakeUserPresets.json` can include other files with the include field in file version 4 and later. Files included by these files can also include other files. If `CMakePresets.json` and `CMakeUserPresets.json` are both present, `CMakeUserPresets.json` implicitly includes `CMakePresets.json`, even with no include field, in all versions of the format.
Users may leverage that feature to have common definitions across different projects.

See [cmake-preset docs](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html#includes)

The conan package manager uses that when generating multiple build configurations, for example:

`CMakeUserPresets.json`:

```json
{
    "version": 4,
    "vendor": {
        "conan": {}
    },
    "include": [
        "~/project/build/CMakePresets.json"
    ]
}
```

`~/project/build/CMakePresets.json`:

```json
{
    "version": 3,
    "vendor": {
        "conan": {}
    },
    "cmakeMinimumRequired": {
        "major": 3,
        "minor": 15,
        "patch": 0
    },
    "configurePresets": [
        {
            "name": "default",
            "displayName": "'default' config",
            "description": "'default' configure using 'Ninja Multi-Config' generator",
            "generator": "Ninja Multi-Config",
            "cacheVariables": {
                "CMAKE_POLICY_DEFAULT_CMP0091": "NEW"
            },
            "toolchainFile": "~/project/build/conan_toolchain.cmake",
            "binaryDir": "~/project/build"
        }
    ],
    "buildPresets": [
        {
            "name": "release",
            "configurePreset": "default",
            "configuration": "Release"
        },
        {
            "name": "debug",
            "configurePreset": "default",
            "configuration": "Debug"
        },
        {
            "name": "relwithdebinfo",
            "configurePreset": "default",
            "configuration": "RelWithDebInfo"
        }
    ],
    "testPresets": [
        {
            "name": "release",
            "configurePreset": "default",
            "configuration": "Release"
        },
        {
            "name": "debug",
            "configurePreset": "default",
            "configuration": "Debug"
        },
        {
            "name": "relwithdebinfo",
            "configurePreset": "default",
            "configuration": "RelWithDebInfo"
        }
    ]
}

```
The plugin current behavior cannot detect the presets coming from the included file.

**Describe the solution you'd like**

As a CMake user who often works with including presets into other presets file, I'd like to have at list the first inclusion handled automatically by the plugin, so that it can see and work with every preset defined in the files included in the top level `CMake[User]Presets.json`.

**Describe alternatives you've considered**

A more complete solution would be handling the inclusion recursively, but that would be more complicated. I guess most cases of preset inclusion happens on the first level only. I don't have data to support that assumption, though.

**Additional context**

Conan users will appreciate the solution.

**Comment by Civitasv** [comment]
> A more complete solution would be handling the inclusion recursively, but that would be more complicated. I guess most cases of preset inclusion happens on the first level only. I don't have data to support that assumption, though.

TODO

**Comment by C0RNPOP** [comment]
From my understanding, the `presets.parse` function only needs to return a list of configure presets or build presets, and the method for doing so does not matter (meaning, `presets.parse` does not have any side-effect such as setting up other variables used later on elsewhere).

Thus, wouldn't it be easier to use the built-in CMake command line option `--list-presets`? See [--list-presets=type](https://cmake.org/cmake/help/latest/manual/cmake.1.html#cmdoption-cmake-list-presets)
You would only need to use `cmake --list-presets=configure` (or `cmake --list-presets=build`) to get a list configure (or build) presets, and parse the result accordingly. 

Using a project generated quickly with [cmake-init](https://github.com/friendlyanon/cmake-init), which generates a `CMakePresets.json` file and a `CMakeUserPresets.json` file, here is the result I get for `cmake --list-presets=configure`

```
Available configure presets:

  "dev-unix"
  "dev"
  "dev-coverage"
  "ci-coverage"
  "ci-sanitize"
  "ci-macos"
  "ci-ubuntu
```

Parsing such a result should be fairly easy. The only downside is that `preset.parse` has an option for including hidden presets, while `cmake --list-presets` does not. However, it doesn't seem like hidden presets are used anywhere in the code, so maybe this is not really an issue.
