### ISSUE TITLE
Option to link compile_commands.json to current directory

### ISSUE THREAD

**Issue by ayles** [Civitasv/cmake-tools.nvim#36]
Would be great to have smth like [that](https://github.com/cdelledonne/vim-cmake/blob/6b7b18130c30e1d498c0ec8fca3c18951273e4ea/autoload/cmake/buildsys.vim#L370)

**Comment by Civitasv** [comment]
This plugin use symlink to achieve that, why not use `.clangd`?

**Comment by ayles** [comment]
But switches between release types are initiated by plugin. It is inconvenient to change path to compilation database every time by hand

**Comment by Civitasv** [comment]
Make sense, I will see how i can implement it.

**Comment by iFuSiiOnzZ** [comment]
Something like this on the in `init.lua:125`, inside `on_success` function after running the CMake command. What I can't figure out how to do is to delete the file when exiting the editor.

```
local compile_commands = config.build_directory.filename .. "/compile_commands.json"
local cmd = "[ -e " .. compile_commands .. " ] && cp " .. compile_commands .. " ."

local handle = io.popen(cmd)
handle:close()
```

**Comment by iFuSiiOnzZ** [comment]
Platform independent solution.

```
diff --git a/lua/cmake-tools/init.lua b/lua/cmake-tools/init.lua
index 7293c22..6cf7518 100644
--- a/lua/cmake-tools/init.lua
+++ b/lua/cmake-tools/init.lua
@@ -127,6 +127,13 @@ function cmake.generate(opt, callback)
       if type(callback) == "function" then
         callback()
       end
+
+      local infile  = io.open(config.build_directory.filename .. "/compile_commands.json", "r")
+      local outfile = io.open("compile_commands.json", "w")
+
+      outfile:write(infile:read("*a"))
+      outfile:close()
+      infile:close()
     end,
     cmake_console_position = const.cmake_console_position,
     cmake_show_console = const.cmake_show_console,

```

**Comment by ayles** [comment]
Is there any reason to copy it instead of just making symlink?

**Comment by iFuSiiOnzZ** [comment]
@ayles Because it should be platform independent and I haven't seen anything in the LUA file api that allows to create symbolic links. On Linux you would use `ln -s` and on Windows `mklink`.

**Comment by Civitasv** [comment]
I've added this ability. See 6e4e422666618d6e9ce0bc78246a6ac0aab94ab1

**Comment by iFuSiiOnzZ** [comment]
Haven't test in on Linux yet. On Windows there are a some problems.


Powershell normal user
```
CMake Error: failed to create symbolic link 'C:\Users\Develop\Projects\ls/compile_commands.json': A required privilege is not held by the client.
```

Powershell with admin privileges
```
:!cmake -E create_symlink cmake_build_Debug/compile_commands.json C:\Users\AndreiAJ\Projects\ls/compile_commands.json
```

**Comment by rohit-kumar-j** [comment]
@iFuSiiOnzZ, I did you try compile_commands with MSVC on powershell?

**Comment by Civitasv** [comment]
> Powershell with admin privileges

When in admin privileges, Was the command successful?

**Comment by iFuSiiOnzZ** [comment]
@rohit-kumar-j I am using mingw, at the moment, so no idea if it works or not.
@Civitasv Nope, I played a bit with Windows policies, but also no luck (Windows 11).

**Comment by Civitasv** [comment]
Can you show the error messages?

**Comment by iFuSiiOnzZ** [comment]
For some reason the neovim log is empty and cmake reports nothing about the error.
What is more strange... I ran `cmake -E create_symlink` from the terminal and it worked.

**Comment by Civitasv** [comment]
Look at [this](https://github.com/Civitasv/cmake-tools.nvim#automatically-setting-your-compile_commandsjson-directory).
