### ISSUE TITLE
Add possibility to read cmake variants from Lua format

### ISSUE THREAD

**Issue by toolcreator** [Civitasv/cmake-tools.nvim#4]
Yes, I think it is okay to read it from a file, just like JSON and YAML format. It's natural to me.

_Originally posted by @Civitasv in https://github.com/Civitasv/cmake-tools.nvim/issues/2#issuecomment-1296276957_

**Comment by Civitasv** [comment]
I just rethink about it, it's actually a little weird for me now. I think I don't want a lua config file in my project. YAML and JSON sounds natural, but maybe lua not.
