### ISSUE TITLE
Be able to configure the kits in the lua file or/and be able to add custom path of the json file

### ISSUE THREAD

**Issue by Hyderman** [Civitasv/cmake-tools.nvim#50]
It could be good to be able to configure directly the kits in lua or at least be able to define a custom path for the json file to avoid to copy/paste the kits in each project.

**Comment by rohit-kumar-j** [comment]
Yes, that would be good, although the auto-detection( for e.g. in windows, [vswhere](https://github.com/microsoft/vswhere)) would be ideal. 

Either running this automatically (on startup once, cache the output as a table, and only relaunch detection manually) OR reverse engineer the paths to visual studio, mingw, gcc, or clang(Not preferable).

But, I do not know about the location for gcc/clang on linux and MacOS. Would be nice if someone would help in this reagrd. (Is there a vswhere cline on linux/MacOS or is it manually speciified/symlinked, etc?)

**Comment by Hyderman** [comment]
The CMake Tools extension of VsCode seems to check the environment path for clang and gcc and like you said vswhere for visual studio.
For the behavior, I think it's pretty good.

Maybe something like that for the auto-detect:
```lua
function os.capture(cmd)
  local f = assert(io.popen(cmd, 'r'))
  local s = assert(f:read('*a'))
  f:close()
  return s
end
local path = os.capture("which clang")
```
and instead of `which` run cmd or powershell for windows.
There is also this `https://github.com/LuaDist/luaex` which can extract the environment, I don't know if it works.

**Comment by Civitasv** [comment]
See #59

**Comment by Civitasv** [comment]
Now it supports specify custom path pf the cmake kits json file.
