### ISSUE TITLE
Persistent output buffers

### ISSUE THREAD

**Issue by rohit-kumar-j** [Civitasv/cmake-tools.nvim#55]
I have been working on a PR for two output buffers. One for all cmake tasks except run, and another exclusively for run/launch tasks. 

The intention for this is to keep track of outputs from all the previous commands that cmake tools generates and provide an additonal way to view the outputs not just with quickfix lists.(... As nature intended.. XD) 

I have setup the window/buffer handling in way that launches a buffer first (if not already exists) that has a unique id that persists across the neovim instance.

The following shortened piece of code is intended to launch a job (using native vim/neovim api) and append to an exisint buffer. Here, the problem is in sending lines to the job with stdin. I would appreciate it, if someone can help on this:

Kindly run it and see the output:

```lua
local function on_stdout(id, data, event) vim.fn.append(vim.fn.line('$') - 1, data) end
local job_id = vim.fn.jobstart({ "pwsh", "-noprofile" }, { on_stdout = on_stdout })

local function callback(input) vim.fn.chansend(job_id, { input, "" }) end

local function goto_buffer_across_all_tabs(bufname)
    for _, tabpage in ipairs(vim.api.nvim_list_tabpages()) do
        vim.api.nvim_set_current_tabpage(tabpage)
        for _, window in ipairs(vim.api.nvim_tabpage_list_wins(tabpage)) do
            local win_bufname = vim.api.nvim_buf_get_name(vim.api.nvim_win_get_buf(window))
            if win_bufname:match(bufname) then
                vim.api.nvim_set_current_win(window)
                return
            end
        end
    end
end

-- vim.cmd([[command! -nargs=* WinGo2 lua goto_buffer_across_all_tabs(<q-args>)]])

local bufnr = vim.api.nvim_create_buf(true, true)
vim.api.nvim_buf_set_name(bufnr, "new")
vim.cmd('vs' .. bufnr)
goto_buffer_across_all_tabs('new')

vim.bo.buftype = "prompt"
vim.api.nvim_get_current_buf()
vim.api.nvim_set_current_buf(bufnr)
vim.fn.prompt_setcallback(bufnr, callback)
vim.keymap.set("n", "<esc>", ":bw!<cr>")
vim.cmd.startinsert()
```

For testing in unix change pwsh to /bin/sh

Currently this is the output:

![image.png](https://github.com/Civitasv/cmake-tools.nvim/assets/37873142/857b4d37-a0e8-44a7-9e48-674a2195b3b0)

**Comment by rohit-kumar-j** [comment]
This is a translation from this video: https://youtu.be/NBGD7GoqafY
Plus some window handling

**Comment by Civitasv** [comment]
Interesting! I will try to test it today.

**Comment by Civitasv** [comment]
Can you describe more about how should I test it? Especially where should I place this chunk of codes in?

**Comment by rohit-kumar-j** [comment]
@Civitasv, I fixed it! (Just changed my approach... :D)

The following is a way to handle a single interactive terminal buffer (1 for cmake build, clean, generate and, cleanrebuild)

In the main PR, How about:
1. Each executable can have a separate terminal instance to run it, with their own args as mentioned by @hfn92 in #53. 
2. Each debug executable can have a separate terminal instance to run it as well, with its own args. 

PS: One weird thing I found out was that on window `chan_send()`ing `\\n` does not work(it acts as a new line). We have to send the enter command as: `cmd .. string.char(13)`. This works both on WSl and windows, so I think we can stick the latter. 

`:source` this lua file: (kindly ignore the bad naming scheme... will fix it in the main PR)
<details>
<Summary>Multi window, Multi tab handling for a single buffer</Summary>

```lua
local term_idx                                      -- This is the buffer number of term
local term_channel                                  -- This is the channel number
local term_height = 10                              -- Terminal height
local multiple_terminals_per_tab = false            -- Prefer to keep false, since we will not close it
local keep_single_terminal_per_tab = true           -- Prefer true if you want to keep only one per tab
local keep_terminal_in_tab_static = true            -- Prefer if you want to use a single static instance
local display_single_window_across_instance = false -- Prefer to keep this false
local vert_split = true

local term_name = "my_term" -- name the channel... like CMakeRun
local positon = 'below'     -- This si the location of inital term generation (as we are using vim api)
local cmd = "ls"
local is_startinsert = true

local previous_window = vim.api.nvim_get_current_win() -- This gives us an anchor... a starting point

---------------------------------------------------------

for i, buf_nr in ipairs(vim.api.nvim_list_bufs()) do
    local name = vim.api.nvim_buf_get_name(buf_nr)
    print(i .. " : " .. buf_nr .. ", name: " .. vim.api.nvim_buf_get_name(buf_nr) .. " type: " .. type(name))
    print("buf exists: " .. tostring(string.match(name, term_name) == term_name))
    local matched = string.match(name, term_name) == term_name
    if matched then
        term_idx = buf_nr
        break
    else
        print("-> no test_buf")
    end
    print(" ")
end

-- Create terminal is not created!

local function is_buffer_hidden_in_current_tab(bufname)
    local bufnr = vim.fn.bufnr(bufname)
    for _, winid in ipairs(vim.api.nvim_list_wins()) do
        if vim.api.nvim_win_get_buf(winid) == bufnr then
            return false -- Buffer is shown in a split
        end
    end
    return true -- Buffer is not shown in any split
end

function _G.getWindowsWithBuffer(bufname)
    local windows = {}
    for _, winid in ipairs(vim.api.nvim_list_wins()) do
        local bufnr = vim.api.nvim_win_get_buf(winid)
        local winbufname = vim.api.nvim_buf_get_name(bufnr)
        if winbufname == bufname then
            table.insert(windows, winid)
        end
    end
    return windows
end

function _G.get_windows_displaying_my_buffer_across_all_tabs(bufname)
    local windows = {}
    for _, tabpage in ipairs(vim.api.nvim_list_tabpages()) do
        vim.api.nvim_set_current_tabpage(tabpage)
        for _, window in ipairs(vim.api.nvim_tabpage_list_wins(tabpage)) do
            local win_bufname = vim.api.nvim_buf_get_name(vim.api.nvim_win_get_buf(window))
            if win_bufname:match(bufname) then
                table.insert(windows, window)
            end
        end
    end
    return windows
end

function _G.is_buffer_displayed_in_current_tab(buf_name)
    local current_tabpage = vim.api.nvim_get_current_tabpage()
    for _, window in ipairs(vim.api.nvim_tabpage_list_wins(current_tabpage)) do
        local win_bufnr = vim.api.nvim_win_get_buf(window)
        local win_bufname = vim.api.nvim_buf_get_name(win_bufnr)
        if win_bufname:match(buf_name) then
            return true
        end
    end
    return false
end

function _G.get_windows_for_buffer_in_current_tab(buf_name)
    local windows = {}
    local current_tabpage = vim.api.nvim_get_current_tabpage()
    for _, window in ipairs(vim.api.nvim_tabpage_list_wins(current_tabpage)) do
        local win_bufnr = vim.api.nvim_win_get_buf(window)
        local win_bufname = vim.api.nvim_buf_get_name(win_bufnr)
        if win_bufname:match(buf_name) then
            table.insert(windows, window)
        end
    end
    return windows
end

function _G.get_terminal_buffer_number_and_channel_number(name)
    local bufinfo = vim.api.nvim_list_bufs()
    for _, bufnr in ipairs(bufinfo) do
        local buftype = vim.api.nvim_buf_get_option(bufnr, 'buftype')
        local bufname = vim.api.nvim_buf_get_name(bufnr)
        local filename = vim.fn.fnamemodify(bufname, ':t')
        print("buftype: " .. buftype .. ", bufname: " .. bufname .. ", filename: " .. filename)
        if buftype == 'terminal' and filename == name then
            -- local term_chan = vim.api.nvim_buf_get_var(bufnr, '&channel')
            local term_chan = vim.api.nvim_call_function('nvim_buf_get_var', { bufnr, 'terminal_job_id' })
            return bufnr, term_chan
        end
    end
    return nil, nil
end

function _G.getWindowNumberByBufferName(bufname)
    local bufnr = vim.fn.bufnr(bufname)
    for _, winid in ipairs(vim.api.nvim_list_wins()) do
        if vim.api.nvim_win_get_buf(winid) == bufnr then
            return vim.api.nvim_win_get_number(winid)
        end
    end
    return nil -- Buffer is not open in any window
end

function _G.closeWindowsByBufferName(bufname)
    local previous_window = vim.api.nvim_get_current_win()

    for _, tabpage in ipairs(vim.api.nvim_list_tabpages()) do
        vim.api.nvim_set_current_tabpage(tabpage)
        for _, window in ipairs(vim.api.nvim_tabpage_list_wins(tabpage)) do
            local win_bufname = vim.api.nvim_buf_get_name(vim.api.nvim_win_get_buf(window))
            if win_bufname:match(bufname) then
                vim.api.nvim_set_current_win(window)
                hide_window()
                vim.api.nvim_set_current_win(previous_window)
                return
            end
        end
    end

    vim.api.nvim_set_current_win(previous_window)
end

local function send_commands_to_terminal(buffer_preset_name, data, is_startinsert, focus_win_nr)
    local bufnr, chan = get_terminal_buffer_number_and_channel_number(buffer_preset_name)
    if chan > 0 then
        vim.api.nvim_chan_send(chan, data .. string.char(13))
    else
        print("chan error!")
    end
    print("previous_window: ")
    print(focus_win_nr)
    vim.api.nvim_set_current_win(focus_win_nr)
    if is_startinsert then
        vim.cmd('startinsert')
    end
end

local function set_new_window_for_buffer(split_win, buffer_idx, dimension)
    if split_win == true then
        vim.cmd('split')
    end
    vim.api.nvim_win_set_buf(0, buffer_idx)
    if vert_split == true then
        vim.api.nvim_win_set_height(0, dimension)
    else
        vim.api.nvim_win_set_width(0, dimension)
    end
    vim.cmd('setlocal noequalalways') -- Avoid resizing the split
    return vim.api.nvim_get_current_win()
end


if term_idx then
    print('terminal buffer exists!')
    -- If user wants only a single buffer across all tabgroups, we skip the logic after this block
    if display_single_window_across_instance == true then
        print('single terminal across tabs!')
        -- Close all windows displaying the terminal buffer
        closeWindowsByBufferName(term_name)
        -- Now split window and launch the task
        local terminal_window = set_new_window_for_buffer(true, term_idx, term_height)
        send_commands_to_terminal(term_name, cmd, is_startinsert, terminal_window)
        --
        -- Next, we check if the user wants single buffer per tab
    elseif keep_single_terminal_per_tab == true then
        if is_buffer_hidden_in_current_tab(term_name) == true then
            print("terminal buffer is hidden!")
            -- Since the buffer is hidden, we open it below the current split
            local terminal_window = set_new_window_for_buffer(true, term_idx, term_height)
            send_commands_to_terminal(term_name, cmd, is_startinsert, previous_window)
            -- Else: Terminal is not hidden in current tabpage
        else
            print("terminal buffer is not hidden!.....")
            -- Since, it is open in another window, we check how many windows display the buffer
            -- Check if user wants to keep the terminal window in this buffer as static
            if keep_terminal_in_tab_static == true then
                print("running cmake task")
                local terminal_window = get_windows_for_buffer_in_current_tab(term_name)[1]
                send_commands_to_terminal(term_name, cmd, is_startinsert, previous_window)
            else --- If user wants location of the single window tab as [[ NOT ]] static location
                print("User wants to replace the loaction of the terminal in this current tab")
                -- If terminal is displayed in a split in the current tab and close it, reopen below the current window
                -- close all the windows/split that display our terminal and reopen
                local windows_that_display_terminal_in_current_tab = get_windows_for_buffer_in_current_tab(term_name)
                for _, win_nr in ipairs(windows_that_display_terminal_in_current_tab) do
                    vim.api.nvim_win_close(win_nr, { force = false }) -- do not force close
                end
                -- Now we re-open a single window below the current window and run the cmake task
                local terminal_window = set_new_window_for_buffer(true, term_idx, term_height)
                send_commands_to_terminal(term_name, cmd, is_startinsert, previous_window)

                -- If the current window in already our terminal, then simply run the terminal cmake tasks,
                -- else close terminal window in this current tab and reopen below current split
            end
        end
    else -- Multiple buffers per tabpage
        if term_idx == vim.api.nvim_get_current_buf() then
            print("run task without splitting")
            set_new_window_for_buffer(false, term_idx, term_height)
            send_commands_to_terminal(term_name, cmd, is_startinsert, previous_window)
        else
            print('create window, load  buffer and run task')
            set_new_window_for_buffer(true, term_idx, term_height)
            send_commands_to_terminal(term_name, cmd, is_startinsert, previous_window)
        end
    end
else
    -- terminal does not exist, as we create the terminal first and immediately name it.
    -- Next time when we get the terminal, we use it's name to get it
    vim.cmd(':' .. positon .. ' :sp' .. ' | :term')
    print("newly creating terminal")
    term_channel = vim.api.nvim_buf_get_option(0, 'channel') -- get terminal channel. Next time, get channel number by name
    vim.api.nvim_buf_set_name(0, term_name)                  -- immediately set name
    set_new_window_for_buffer(false, 0, term_height)
    send_commands_to_terminal(term_name, cmd, is_startinsert, previous_window)
end


local term_buffer_nr, term_channel_nr = get_terminal_buffer_number_and_channel_number('my_term')

print("term_buffer_nr: " .. term_buffer_nr .. ", term_channel_nr: " .. term_channel_nr)

```

</details>

**Comment by rohit-kumar-j** [comment]
You can set `false` or `true` for various setting and check it.

**Comment by Civitasv** [comment]
Maybe you can make a PR, so I can get a test environment?

**Comment by rohit-kumar-j** [comment]
> Multi window, Multi tab handling for a single buffer

You can directly source this file without any dependencies.

**Comment by Civitasv** [comment]
And so that we can keep the discussion in that PR.

**Comment by rohit-kumar-j** [comment]
It is only for window/buffer handling. The key to make the terminals interactive is to not pass any `cmd` after `:term` in `:term cmd`, and then use `vim.api.nvim_chan_send(chan, data)` to execute commands, but also keep it persistent.

**Comment by Civitasv** [comment]
Okay.

**Comment by rohit-kumar-j** [comment]
I will start creating a PR for this in sometime, can you kindly test this lua file and let me know any changes?

**Comment by Civitasv** [comment]
![test](https://github.com/Civitasv/cmake-tools.nvim/assets/37768049/ff21778c-12e2-457b-8051-145e3045629e)
Don't know if it works fine?

**Comment by rohit-kumar-j** [comment]
The change the options on the top of the file. you can disable the print statements

**Comment by rohit-kumar-j** [comment]
> To see the effect, I can just source this file?

Yes

**Comment by Civitasv** [comment]
I think it works as expected. Time to make a PR. :smile_cat:

**Comment by rohit-kumar-j** [comment]
Primarily these options:
```lua
local multiple_terminals_per_tab = false            -- Prefer to keep false, since we will not close it
local keep_single_terminal_per_tab = true           -- Prefer true if you want to keep only one per tab
local keep_terminal_in_tab_static = true            -- Prefer if you want to use a single static instance
local display_single_window_across_instance = false -- Prefer to keep this false
local vert_split = true

```

**Comment by rohit-kumar-j** [comment]
@Civitasv, I am wokring on this, but the current method of sending commands to job control (via cmakegenerate or cmakebuild, etc...) all check if there is an active job via a pid for the job. 

Bu if it is to be executed in the terminal, is there a way to check of the terminal is ready for user input or has completed the previous command that was sent to the command with `chansend`? 

So as to not keep sending the same command multiple times to terminals by mistake?

**Comment by Civitasv** [comment]
Is there something like `mutex` lock in lua?

**Comment by rohit-kumar-j** [comment]
No not natively. What's your idea for dealing with this?

**Comment by Civitasv** [comment]
Is it suitable to use coroutine? I think coroutine should use with async operation.

**Comment by Civitasv** [comment]
I wonder if it is okay to just let it busy wait?

**Comment by rohit-kumar-j** [comment]
How do we do that?

**Comment by Civitasv** [comment]
Can we use this [async](https://github.com/nvim-lua/plenary.nvim#plenaryasync) feature of plenary?

**Comment by rohit-kumar-j** [comment]
Can you an async give an example with this?

```lua
function utils.has_active_job()
  if not utils.job or utils.job.is_shutdown then
    return true
  end
  utils.error(
    "A CMake task is already running: "
    .. utils.job.command
    .. " Stop it before trying to run a new CMake task."
  )
  return false
end
```

These checkers are remaining.

**Comment by Civitasv** [comment]
Maybe the structure will be like this:

```lua
local async = require("plenary.async")

local sender, receiver = async.control.channel.mpsc()

local function provider(n)
  sender.send(n)
end

local function consumer()
  local value = receiver.recv()
  print("received:", value)
end

provider(10)
consumer()
provider(20)
consumer()
provider(30)
consumer()
provider(40)
consumer()

--[[ this will print 10, 20, 30, 40 ]]
```

**Comment by Civitasv** [comment]
With a `provider` call, there will be a `consumer` call. Do you think it is okay?

**Comment by rohit-kumar-j** [comment]
would this work with:

`:lua vim.api.nvim_chan_send(vim.api.nvim_buf_get_var(vim.api.nvim_win_get_buf(vim.api.nvim_get_current_win()),'terminal_job_id'), 'ls\r')`

after `:term`?

**Comment by rohit-kumar-j** [comment]
> With a provider call, there will be a consumer call. Do you think it is okay?

I don't think whis will work. async does not seem to know the child process's command execution

**Comment by rohit-kumar-j** [comment]
Can we get status of child process (`:term`'s) with the PID of the process? 

That would be enough to tell if the terminal is ready for new inputs.

**Comment by Civitasv** [comment]
http://neovim.io/doc/user/nvim_terminal_emulator.html#terminal-status

**Comment by Civitasv** [comment]
> So as to not keep sending the same command multiple times to terminals by mistake?

Can you give me an example about this?

**Comment by rohit-kumar-j** [comment]
Let us say that I hit (shortcut keybindings) `CMakeGenereate` multiple times in sequence, by mistake. 

Then I will be queueing commands to be sent to the terminal. (Tried this with `Start Sleep -Seconds 10` in powershell, where I sent this twice. After the 1st 10 seconds, it ran the second one).

This is undesirable as the nvim_chan_send() will queue the commands and not disregard commands if terminal is busy.

**Comment by Civitasv** [comment]
Can we get notified when command finished?

**Comment by rohit-kumar-j** [comment]
Does not seem like it. When we run `cmake --build` for example, it ends with various outputs with different build systems and each command has a different final output. 

The only time, we can detect if the process has exited (sucessfully or not), would be when the terminal is ready for the next user input.

Something like when we do `ls` on a large directory, we can detect that it finished only when we see the input prompt: `~$`

**Comment by rohit-kumar-j** [comment]
@Civitasv, check out this [hacky solution](https://github.com/stevearc/oil.nvim/blob/9f2f50f9158b42e72bbf9d7d3d1e4bb9aba8b245/lua/oil/adapters/ssh/connection.lua#L270-L276) from [reddit](https://www.reddit.com/r/neovim/comments/13r10e3/comment/jlibr0b/?context=3). 

We can schedule wrap a function to get lines immediately capture lines on function completion and only trigger it when we get the output is re-read from the terminal buffer, which would happen on function completion.

**Comment by rohit-kumar-j** [comment]
@Civitasv, I found a possible way to do this: We create and track an env varaible(`$env:CMAKETOOLS_NVIM_MAIN_OUTPUT`). Each time the user sends a command we query this variable , and do some if-else logic based on its value. 

(Although this can be implemented if we can silently query environment variables through the terminal...) 

The variable will be set to true only after the job is run. Otherwise, we set it to a random string.

If true, then the job completed. If false, the stderr. Else we set a string value(`"CMakeToolsRunning"`) to this variable. 

Works well in powershell:
![image](https://github.com/Civitasv/cmake-tools.nvim/assets/37873142/d6cbecae-30ae-457b-a588-630b0aa80ffa)

If the chain of commands are interrupted, it does not change the value of the env variable:
![image](https://github.com/Civitasv/cmake-tools.nvim/assets/37873142/99aa0e36-af62-424f-9014-c3c9c626dad3)

We can do some conditional logic with this...

I have used these commands to issue commands to the terminal:

`:sp | :term ` Creates the terminal. The follwowing commnads need the terminal buffer to be in focus(This will not be necessary in the actual implementaion, just in this test):

set status of var before running task:

```lua
:lua vim.api.nvim_chan_send(vim.api.nvim_buf_get_var(vim.api.nvim_win_get_buf(vim.api.nvim_get_current_win()), "terminal_job_id"), "$env:CODE='THIS IS SET BEFORE INTERRUPTION' \r")
```
If interrupted, this is not changed!

Next, Run task:
```lua
:lua vim.api.nvim_chan_send(vim.api.nvim_buf_get_var(vim.api.nvim_win_get_buf(vim.api.nvim_get_current_win()), "terminal_job_id"), "echo '===BEGIN==='; Start-Sleep -Seconds 10; $env:CODE=$? ; echo '===DONE'$env:CODE'==='; $env:CODE \r")
```

Check status of var:
```lua
:lua vim.api.nvim_chan_send(vim.api.nvim_buf_get_var(vim.api.nvim_win_get_buf(vim.api.nvim_get_current_win()), "terminal_job_id"), "if($env:CODE = $true){echo 'this is true'} elseif($env:CODE = $true){echo 'this is true'} else {$env:CODE} \r")
```

Can you test this in linux with linux specific commands?

**Comment by rohit-kumar-j** [comment]
Finally!

@Civitasv, check this out:

Spwanning a child process does the trick... (since we can get list of child process list and compare if any child processes are active)
![image](https://github.com/Civitasv/cmake-tools.nvim/assets/37873142/2a02c5bf-8d3a-449e-af2f-eeb8cb6298ca)

Including multiple processes...

![image](https://github.com/Civitasv/cmake-tools.nvim/assets/37873142/cf0b07b9-9fcb-43eb-b19a-06b9430669fe)

After both child processes exit:

![image](https://github.com/Civitasv/cmake-tools.nvim/assets/37873142/a3866642-fdea-481f-84f4-38ba10b11b3e)

So, when there are no child processes left, then we can issue commands to the terminal buffer.
No need for exit code, as output will be directly displayed in the window buffer.

**Comment by rohit-kumar-j** [comment]
Is this a good strategy?

**Comment by Civitasv** [comment]
That’s really really good!

**Comment by rohit-kumar-j** [comment]
@Civitasv, can you check [this](https://www.reddit.com/r/neovim/comments/13sd7pd/child_process_output_from_terminal_buffer_is/?f=flair_name%3A%22Need%20Help%22) out(currently, where I am stuck 😅)

**Comment by Civitasv** [comment]
I will test it tomorrow. Currently I have no clue.

**Comment by rohit-kumar-j** [comment]
So sorry..., the issue was specific to powershell, an not neovim. Found a way to wrap the commands inside a process and get the child pids for it:

https://github.com/neovim/neovim/issues/23777#issuecomment-1565397726

There should be a similar way to do this for unix.
