### ISSUE TITLE
[Development discussion] CMake Variants.

### ISSUE THREAD

**Issue by Civitasv** [Civitasv/cmake-tools.nvim#6]
Still have problems in my computer.
Keep notifying can't open file.

_Originally posted by @Civitasv in https://github.com/Civitasv/cmake-tools.nvim/issues/5#issuecomment-1296291628_

**Comment by Civitasv** [comment]
@toolcreator we can discuss it here.

**Comment by toolcreator** [comment]
Haven't had that error message, do you have any instruction on how to reproduce the issue?
Is there more error output, e.g., a file and line number where this happens?

**Comment by Civitasv** [comment]
I think it's actually error of Treesitter.

**Comment by Civitasv** [comment]
> I think it's actually error of Treesitter.

No, when you don't provide `cmake-variants.json` and `cmake-variants.yaml`, it will popup as below:

![image](https://user-images.githubusercontent.com/37768049/199057477-ff10d7b3-cce2-447f-b125-cfecc8e6fafa.png)

File structure:

![image](https://user-images.githubusercontent.com/37768049/199057568-a2cb640e-c3a5-4e7e-9816-c9ac1b29f36b.png)

**Comment by toolcreator** [comment]
Thanks for testing the JSON, it's nice to hear it just works :)

Regarding the bug you found, please see #9.

During testing I saw you added the detailed option descriptions in cc23b3617b3f14ca65a04f15f70c9d4532790b7d.
I'd argue for removing this (or make it optional, or visualized differently), because it can really ruin the output: ![Screenshot_20221031_210506](https://user-images.githubusercontent.com/53090917/199101501-b6a5139a-cfd4-41e5-9c82-9f58c95d5c6f.png)

**Comment by Civitasv** [comment]
I added it cause vscode support this feature:
![image](https://user-images.githubusercontent.com/37768049/199134741-9837f140-0c37-48a6-922d-82cec3057781.png)

Yes, it's a little weird, I will make it optional and provide a `message length` option. When exceed message length, just show `...`.

What's your opinion about this solution.

**Comment by Civitasv** [comment]
I've added option to enable detailed message or not, and when enabled, a max_length is provided for control message length.

![Screenshot from 2022-11-01 09-52-17](https://user-images.githubusercontent.com/37768049/199141720-063bfd9c-5450-4b31-b75a-dec42213023f.png)

**Comment by toolcreator** [comment]
That is really awesome!
Thanks for making it so configurable, and thanks for the mention in the readme!
