### ISSUE TITLE
Terminal mode: When checking if there is a process attached to terminal, it should not block neovim instance

### ISSUE THREAD

**Issue by Civitasv** [Civitasv/cmake-tools.nvim#60]
Currently, I use these codes to check if there is a process is finished, which is need to chain callback.

https://github.com/Civitasv/cmake-tools.nvim/blob/3e5f768977a7825e70335feff2cfac56e54ac33b/lua/cmake-tools/terminal.lua#LL542C1-L560C6

But this will block neovim instance, we should find a non-blocking or async way to check this.

**Comment by rohit-kumar-j** [comment]
Posible solution...?
If we do a background non-blocking `vim.wait()` that looks inside the build directory every n milliseconds until the currently running cmake produces the `CMakeCache.txt` or something like that which tells the status of the cmake process is completed, once it finds this (effectively a more verbose on_success() condition), maybe even the timestamp of the file... We can then chain the next command with a small delay. 

We will need to create new functions for checking status of files like how the codemodel targets are obatined...

**Comment by Civitasv** [comment]
Okay, hopefully someone can anwser it. :smile:

**Comment by rohit-kumar-j** [comment]
Seems like this can be accomplished by writing a [dummy query into a file](https://discourse.cmake.org/t/is-there-a-way-to-check-when-any-cmake-task-has-finished-purely-from-the-filesystem-build-directory/8271/4?u=j_rohit). 

@Civitasv, do you have any idea how we may do this?

**Comment by Civitasv** [comment]
I've researched some plugins about terminal, cannot find a suitable solution to get notified when terminal executes commands successfully. But I find another way, See it at #63.

**Comment by rohit-kumar-j** [comment]
Nice! That is a simple and effective solution :D
