### ISSUE TITLE
Add setup of NvimTree in FAQs

### ISSUE THREAD

**Issue by rohit-kumar-j** [Civitasv/cmake-tools.nvim#64]
I forgot to add this in the [Multiple Buffers PR](https://github.com/Civitasv/cmake-tools.nvim/pull/58):

For users that are using nvim-tree, they need to add this for preserving the size of window when opening or closing the tree and avoid resizing. Otherwise the constant resizing can get very annoying. 

```lua
require("nvim-tree").setup {
    --
    view = {
      preserve_window_proportions = true,
      ---
    },
}
```
Can you add this in the docs?

**Comment by Civitasv** [comment]
How does it affect to our plugin?

**Comment by Civitasv** [comment]
Can add this at section [terminal](https://github.com/Civitasv/cmake-tools.nvim/blob/master/docs/howto.md#experimental-awalys-use-terminal)

**Comment by rohit-kumar-j** [comment]
> How does it affect to our plugin?

It does not. But I had a hard time with keeping the size constant, Didn't know what the issue was till I did a little digging. 😅

> Can add this at section [terminal](https://github.com/Civitasv/cmake-tools.nvim/blob/master/docs/howto.md#experimental-awalys-use-terminal)

Nice.
