### ISSUE TITLE
Launch terminal command chaining issue.

### ISSUE THREAD

**Issue by rohit-kumar-j** [Civitasv/cmake-tools.nvim#66]
In the **Run/Launch terminal**, when build commands are chained(default build before run), it does not move out of build directory to build, but builds in the same directory, and errors!

```bash
D:/Koala/build ~$ cmake --build build --target testing_ptr && cd "D:\Koala\build" && .\testing_ptr.exe
Error: D:/Koala/build/build is not a directory
```

It should be:

```bash
D:/Koala/build ~$ cd "D:\Koala" cmake --build build --target testing_ptr && cd "D:\Koala\build" && .\testing_ptr.exe
...
...
```

However, this works the first time as there is no full cmd.

### Note, this is an edge case and I did not have this problem for all targets.

**Comment by Civitasv** [comment]
Okay. I will merge it.

**Comment by Civitasv** [comment]
Oops! I made a mistake. You should not
