### ISSUE TITLE
Test Framework Support: How should this plugin support Test Frameworks such as GoogleTest, Ctest, etc?

### ISSUE THREAD

**Issue by Civitasv** [Civitasv/cmake-tools.nvim#68]
**Useful Link:**

1. [cmake-gtest](https://github.com/hfn92/cmake-gtest.nvim)
2. [ctest with cmake](https://cmake.org/cmake/help/book/mastering-cmake/chapter/Testing%20With%20CMake%20and%20CTest.html)
3. [googletest](https://google.github.io/googletest/)

**Comment by hfn92** [comment]
I have a prototype for ctest https://github.com/hfn92/cmake-tools.nvim/tree/ctest This is pretty much all I would've added for myself

**Comment by rohit-kumar-j** [comment]
+1 ctest would be a good additon to cmaketools as it comes with vanilla cmake.
Seems like currently it uses quickfix terminals. Is this WIP? I will try and port it to the terminal buffers + Windows10 support(Later when I find the time).

I think a single terminal would be nice for the ctests to happen: `[CMakeTools] CTest`? How about this?

**Comment by Civitasv** [comment]
> I think a single terminal would be nice for the ctests to happen: `[CMakeTools] CTest`? How about this?

Yeah. It’s convenient.

**Comment by hfn92** [comment]
> +1 ctest would be a good additon to cmaketools as it comes with vanilla cmake. Seems like currently it uses quickfix terminals. Is this WIP? I will try and port it to the terminal buffers + Windows10 support(Later when I find the time).
> 
> I think a single terminal would be nice for the ctests to happen: `[CMakeTools] CTest`? How about this?

I'd want tests to run in quickfix so that I can jump directly to test errors. That was my whole reason for writing the gtest plugin. How about making it an option at least?

**Comment by Civitasv** [comment]
Yeah, for sure, we should provide two apis, one for quickfix, another for terminal.

**Comment by Civitasv** [comment]
So the detailed logic should be placed in quickfix.lua and terminal.lua, and ctest.lua just calls them.

**Comment by Civitasv** [comment]
And I have a question, if tests are launched in quickfix, what will happen if it should accept values from stdin? Like cin >> x;

**Comment by hfn92** [comment]
Looks like it freezes. But imo tests like those written with gtest shouldn't do things like that. (Btw when trying to debug it just crashes my session when reaching `std::cin`. But that could be a problem elsewhere)

**Comment by Civitasv** [comment]
> Btw when trying to debug it just crashes my session when reaching `std::cin`. But that could be a problem elsewhere

Yeah. Too many changes recently, maybe I forgot to add some logics.

**Comment by Civitasv** [comment]
> Looks like it freezes. But imo tests like those written with gtest shouldn't do things like that.

Yeah, but sometimes people want that. We should make it an option.

**Comment by rohit-kumar-j** [comment]
> > +1 ctest would be a good additon to cmaketools as it comes with vanilla cmake. Seems like currently it uses quickfix terminals. Is this WIP? I will try and port it to the terminal buffers + Windows10 support(Later when I find the time).
> > I think a single terminal would be nice for the ctests to happen: `[CMakeTools] CTest`? How about this?
> 
> I'd want tests to run in quickfix so that I can jump directly to test errors. That was my whole reason for writing the gtest plugin. How about making it an option at least?

Ooh nice. I think the quickfix method should be the default if you can quickly jump in between errors directly with the quickfix list.

**Comment by ErezAmihud** [comment]
There is also [neotest-gtest](https://github.com/alfaix/neotest-gtest) for neotest integration. I could not get it to work properly but it can be use a base to some of the features needed

**Comment by Civitasv** [comment]
> There is also [neotest-gtest](https://github.com/alfaix/neotest-gtest) for neotest integration. I could not get it to work properly but it can be use a base to some of the features needed

Thanks, I shall review that repo someday.

**Comment by hrzlgnm** [comment]
I'd go for cmake ctest, as it supports integration with other testing frameworks. Or the other way around, most testing framework have at leas documentation on how to integrate with ctest, like  for example https://github.com/doctest/doctest

**Comment by Civitasv** [comment]
I've added ctest support(though very naive), now you can use `CMakeRunTest` to run tests with your specified executor. Like:

https://github.com/Civitasv/cmake-tools.nvim/assets/37768049/15875b1d-bff4-416e-a9a1-3117ba786c9e

**Comment by Civitasv** [comment]
Ctest will use *Executor* to run commands.
