### ISSUE TITLE
Quickfix: Only scroll to bottom if it was previously at the bottom

### ISSUE THREAD

**Issue by hfn92** [Civitasv/cmake-tools.nvim#69]
I think the quickfix window should stop auto scrolling if the window is currently not at the bottom.

For example while a longer operation is running I notice something and scroll up to take a look. But the window keeps scrolling down. I think the auto scrolling should stop in this case and only continue once I manually scroll back to bottom.

What do you think? I think it would be useful option (or even be the default)

**Comment by Civitasv** [comment]
I agree with you. Maybe, by default, the quickfix console should automatically scroll down. But once the user have manually scrolled the quickfix, we stop scrolling down. 

Q: How do we check if the user have manually scrolled?
A: Todo

**Comment by hfn92** [comment]
Possibly we can find something here?
https://github.com/skywind3000/asyncrun.vim/wiki/Scroll-the-quickfix-window-only-if-cursor-is-on-the-last-line
https://github.com/skywind3000/asyncrun.vim/blob/master/plugin/asyncrun.vim#L418

**Comment by Civitasv** [comment]
That’s helpful.

**Comment by Civitasv** [comment]
See #55349fc6461ba01119ba193ce736e904d4534d14, Not the quickfix works like https://github.com/skywind3000/asyncrun.vim/wiki/Scroll-the-quickfix-window-only-if-cursor-is-on-the-last-line#gasyncrun_last--0-default.

**Comment by hfn92** [comment]
Very cool thanks :+1:
