### ISSUE TITLE
Support  for Project Specific `CMakeSettings.json` or `CMakePresets.json`?

### ISSUE THREAD

**Issue by LinHeLurking** [Civitasv/cmake-tools.nvim#7]
**Describe the problem or limitation you are having**

Sometimes we're configuring with certain project specific settings like `-DXXX_ROOT=<...>`. Such settings might be dependent on host computer environments therefore they are not suitable to directly hard coded in `CMakeLists.txt`.

**Describe the solution you'd like**

Support (partially) parsing `CMakeSettings.json` or `CMakePresets.json` like VS/VSC to add or override some global cmake settings.

**Comment by Civitasv** [comment]
Will be considered.

**Comment by Civitasv** [comment]
Hey, Please see the latest commit, Now it supports `CMakePresets.json`.

**Comment by LinHeLurking** [comment]
> Hey, Please see the latest commit, Now it supports `CMakePresets.json`.

Great! Thank a lot! 😘

**Comment by lbiaggi** [comment]
If you have multiple presets, it doesn't like... :(
e.g: https://invent.kde.org/plasma/plasma-firewall/-/blob/master/CMakePresets.json

**Comment by Civitasv** [comment]
Oops, what's the error?

**Comment by Civitasv** [comment]
Oh, my bad, I misunderstand the docs from cmake. Looking forward for your PR.

**Comment by Civitasv** [comment]
See Pr #14 for bug fix.

**Comment by lbiaggi** [comment]
@Civitasv can you review the function `config:build_targets()`? I think there is a logic error in it.

**Comment by lbiaggi** [comment]
Nevermind, I found the problem the following snippet should be called before presets.
```
    if not config.build_type then
        return cmake.select_build_type(function()
            cmake.generate(opt, callback)
        end)
    end

    config:generate_build_directory()
```

**Comment by lbiaggi** [comment]
I think @LinHeLurking should test and provide feedback about the feature :smile:

**Comment by LinHeLurking** [comment]
It's perfect! I add slightly changed some logics during building (see #16 ). Now it support to build target `all` if you do not specify any build presets, which is the same behavior as VS Code & VS.

**Comment by thetic** [comment]
This doesn't appear to respect the `binaryDir` set in my presets file. `:CMakeBuild` displays:

```
    Error: could not load cache
```
