### ISSUE TITLE
Key not found: terminal_job_id

### ISSUE THREAD

**Issue by hfn92** [Civitasv/cmake-tools.nvim#71]
Recently I've been getting following sporadic errors when using `CMakeRun` or similar.

```
stack traceback:
        [C]: in function 'nvim_buf_get_var'
        .../nvim/lazy/cmake-tools.nvim/lua/cmake-tools/terminal.lua:170: in function 'send_data_to_terminal'
        .../nvim/lazy/cmake-tools.nvim/lua/cmake-tools/terminal.lua:461: in function 'execute'
        ...are/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/utils.lua:74: in function 'execute'
        ...hare/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:417: in function 'callback'
        ...hare/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:309: in function 'on_success'
        .../nvim/lazy/cmake-tools.nvim/lua/cmake-tools/quickfix.lua:44: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
Error executing Lua callback: .../nvim/lazy/cmake-tools.nvim/lua/cmake-tools/terminal.lua:10: Key not found: terminal_job_pid
```

```
Error executing Lua callback: .../nvim/lazy/cmake-tools.nvim/lua/cmake-tools/terminal.lua:10: Key not found: terminal_job_pid
stack traceback:
        [C]: in function 'nvim_buf_get_var'
       .../nvim/lazy/cmake-tools.nvim/lua/cmake-tools/terminal.lua:10: in function 'has_active_job'
        ...are/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/utils.lua:130: in function 'has_active_job'
        ...hare/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:477: in function <...hare/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:474>
Error executing Lua callback: .../nvim/lazy/cmake-tools.nvim/lua/cmake-tools/terminal.lua:10: Key not found: terminal_job_pid
```

**Steps to reproduce**
It occurs randomly when trying to run a target. Sometimes right after starting nvim, sometimes after using nvim for a while. After getting the first error, the second error occurs consistently every time I try to run. I have to restart nvim at that point.

**Environment**
OS: Linux and Windows WSL (not sure about native windows)

**Comment by Civitasv** [comment]
@rohit-kumar-j do you have any idea?

**Comment by rohit-kumar-j** [comment]
I have faced this issue myself and stick to generating the project first, then building and then running. But as OP mentioned, it is not consistent. 

The issue seems to be that we might need to do vim.wait() instead of vim.cmd() when we spawn new terminals as the terminal might not launch before we request it's `terminal_job_pid`. Although I haven't had the time to test this myself.

If we do vim.wait() when we create the terminal, this would ve a blocking call. Potentially freezing the nvim instance until the terminal prompt opens up.

**Comment by doupongzeng** [comment]
Hi, I have a very similar bug that is 100% reproducible, perhaps we can address this one first #74

**Comment by Civitasv** [comment]
> After getting the first error, the second error occurs consistently every time I try to run.

Fixed this at #74.

**Comment by Civitasv** [comment]
And I cannot reproduce the first error.

**Comment by rohit-kumar-j** [comment]
Thanks for fixing this! 
If there are any other bugs, please do not hesitate to discuss. I did not test everything as throughly as I would have wanted when developeing the terminal buffers.

**Comment by Civitasv** [comment]
Closed for now. Feel free to open it when you encounter this problem again.

**Comment by Civitasv** [comment]
Sorry, but I cannot reproduce this problem. Can you find a way to reproduce it steadily?

**Comment by hfn92** [comment]
I'll try. I seems much rarer now but still happens from time to time.

**Comment by hfn92** [comment]
Thanks :+1:
