### ISSUE TITLE
When exiting the current CMakeRun-terminal and cmd CMakeRun, an error occurs.

### ISSUE THREAD

**Issue by doupongzeng** [Civitasv/cmake-tools.nvim#74]
**Bug description**

When exiting the current CMakeRun-terminal and cmd CMakeRun, an error occurs.

**Steps to reproduce**
1. cmd: CMakeRun
2. terminal: exit
3. cmd: CMakeRun
5. Error executing Lua callback: .../nvim/lazy/cmake-tools.nvim/lua/cmake-tools/terminal.lua:10: Invalid buffer id: 17                                                                    
stack traceback:                                                                                                                                                                       
        [C]: in function 'nvim_buf_get_var'                                                                                                                                            
        .../nvim/lazy/cmake-tools.nvim/lua/cmake-tools/terminal.lua:10: in function 'has_active_job'                                                                                   
        ...are/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/utils.lua:130: in function 'has_active_job'                                                                                  
        ...hare/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:399: in function <...hare/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:398>

<details><summary>Minimal configuration</summary>
default
</details>

**Expected behavior**

no errors, running the executor

**Environment**

- OS: Ubuntu
- Desktop environment: Gnome
- Plugins commit hash: the main branch

**Comment by Civitasv** [comment]
Fixed. Please use latest commit.

**Comment by doupongzeng** [comment]
Looks great
