### ISSUE TITLE
Unable to disable cmake generate auto-generation on save

### ISSUE THREAD

**Issue by festeh** [Civitasv/cmake-tools.nvim#75]
**Bug description** 
Hi! When the module gets imported, then an autocommand will be generated [here](https://github.com/Civitasv/cmake-tools.nvim/blob/master/lua/cmake-tools/init.lua#L1011C1-L1011C1), using default value for `cmake_regenerate_on_save` (true). So, after config is created, `cmake_regenerate_on_save` will have no effect.

**Steps to reproduce**
```
require("cmake-tools").setup {
    cmake_regenerate_on_save = false,
}
```

Re-generation is still triggered, which is disturbing, when using auto-save plugin. If you're interested, I can make a PR.

**Comment by Civitasv** [comment]
Yeah. That’s a bug. Pr is welcome!
