### ISSUE TITLE
Not generating compile_commands.json?

### ISSUE THREAD

**Issue by hsetlik** [Civitasv/cmake-tools.nvim#80]
Hi everyone,

First off I really appreciate this plugin, it's made the transition to nvim from vscode way more pleasant. 

I ran into an issue while working on an existing CMake project in neovim for the first time. Configuring and building with cmake-tools works correctly, but the code is covered in erroneous warnings from clangd;  it looks like `compile_commands.json` isn't being generated anywhere in the build folder. My setup for `cmake-tools` is exactly the same as the readme in this repo, and I set up clangd via Mason and lspconfig like so:
```
lspconfig["clangd"].setup({
	capabilities = capabilities,
	on_attach = on_attach,
	on_new_config = function(new_config, new_cwd)
		local status, cmake = pcall(require, "cmake-tools")
		if status then
			cmake.clangd_on_new_config(new_config)
		end
	end,
})
```
Am I misunderstanding something about how this works or where `compile_commands.json` should be? Do I need to change the values of `cmake_soft_link_compile_commands` or `cmake_compile_commands_from_lsp` in the setup function? I'm on nvim version 0.9.0 and macOS Ventura 13.4 if that's relevant.
Any advice is much appreciated!

**Comment by Civitasv** [comment]
Set `cmake_compile_commands_from_lsp` to true.

**Comment by hsetlik** [comment]
Ok, just tried with `cmake_compile_commands_from_lsp` set to true and `cmake_soft_link_compile_commands` set to false like the readme suggests and still have the same problem. Is there a way to tell where the file is supposed to be generated?

**Comment by Civitasv** [comment]
It should be in the build dir. When cmake_compile_commands_from_lsp option is on, this location will be passed to clangd lsp. So you can check if this file is generated in your build directory.

**Comment by hsetlik** [comment]
Thanks for the reply, I have my build directory set like this: `cmake_build_directory = "build"` rather than the default empty string. I still don't see the file in the top level "build" folder, do I need to specify that somewhere else? I also have `cmake_generate_options = { "-DCMAKE_EXPORT_COMPILE_COMMANDS=1" }` in my setup function, if that's relevant.

**Comment by Civitasv** [comment]
Use “cmake -B build -S . -DCMAKE_EXPORT_COMPILE_COMMANDS=1”, then see if compile commands file is in the build directory.

**Comment by hsetlik** [comment]
Ok, I just tried that and it looks like compile_commands.json generates correctly except for when I use the Xcode generator, according to CMake docs it's not supported: https://cmake.org/cmake/help/latest/variable/CMAKE_EXPORT_COMPILE_COMMANDS.html
There is [a way](https://stackoverflow.com/questions/71258617/how-to-generate-compiler-command-json-using-xcode-via-cmake) to generate it with Xcode's command line tools.

**Comment by Civitasv** [comment]
Oh, then you can add -Gninja to generate options.

**Comment by hsetlik** [comment]
Ok just tried it, everything does work correctly with Ninja. If anyone does need to use the Xcode generator, adding this to the end of my CMakeLists.txt also worked:
```
if(${CMAKE_GENERATOR} STREQUAL "Xcode" AND ${CMAKE_EXPORT_COMPILE_COMMANDS})
 set(XC_PROJ_PATH "${CMAKE_BINARY_DIR}/${PROJECT_NAME}.xcodeproj")
 set(CC_OUTPUT_PATH "${CMAKE_BINARY_DIR}/compile_commands.json")
 execute_process(COMMAND "xcodebuild -project ${XC_PROJ_PATH} | xcpretty -r json-compilation-database --output ${CC_OUTPUT_PATH}")
endif()
```
