### ISSUE TITLE
How to set Ninja to generate cmake-project?

### ISSUE THREAD

**Issue by taynpg** [Civitasv/cmake-tools.nvim#81]
because I use MSVC compiler，so the default generate style can't export the compile_commands.json file，and the clangd can't user this file.

**Comment by Civitasv** [comment]
Use CMakeGenerate -G Ninja

**Comment by taynpg** [comment]
Cool，Thanks very much.

**Comment by Civitasv** [comment]
And you can add -G Ninja to cmake_generate_options at setup function.

**Comment by taynpg** [comment]
Ok，Thank you very much for your help,

**Comment by Civitasv** [comment]
You’re welcome. Closed for now.
