### ISSUE TITLE
cmake variant: cursed folder names

### ISSUE THREAD

**Issue by Gerodote** [Civitasv/cmake-tools.nvim#83]
**Bug description**

I wrote a cmake-variants.yaml  ... 
then I tried to use it. CMakeSelectBuildType, set.

CMakeRun

  then i discovered that no comment ( # line ) in yaml supported ( some really strange cmake errors ). 

ok, delete comments, try again.

a lot of such CMake warnings:
![image](https://github.com/Civitasv/cmake-tools.nvim/assets/58738099/9bb7910d-3c6e-4a49-9716-255f6e098fc4)

and interesting new folder names ( cmake_build_Debug + ... ) :
![image](https://github.com/Civitasv/cmake-tools.nvim/assets/58738099/f13ae866-ed7b-4383-a80b-c663156dab60)

Ok, let's rename options from "cpm_modules" to just cpm_modules. 
Ok, it works. 
![image](https://github.com/Civitasv/cmake-tools.nvim/assets/58738099/f8c08383-880f-43dc-8696-38b5e708b643)
Though, folder name is cursed.
Then, if type `:CMakeRun` and build an executable it will fail because of cursed names:
![image](https://github.com/Civitasv/cmake-tools.nvim/assets/58738099/3f54aacc-b642-49c7-aa61-8e3250edbc2d)

also it makes cpm_modules folder in the way: `"cpm_modules` and `;cpm_modules` if it's written in cmake-variants.yaml as `"cpm_modules"` .

I'll put here my cmake-variants.yaml:

```
buildType:
  default: debug
  choices:
    debug:
      short: Debug
      long: Emit debug information
      buildType: Debug
    release:
      short: Release
      long: Optimize generated code
      buildType: Release
    asan:
      short: Asan
      long: Instrument with Address Sanitizer
      buildType: Asan
    tsan:
      short: Tsan
      long: Instrument with Thread Sanitizer
      buildType: Tsan
cacheCPMPackages:
  default: cpm_modules
  choices:
    dotcache:
      short: .cache_cpm_modules
      long: Save modules in .cache/cpm_modules
      settings:
        CPM_SOURCE_CACHE: .cache/cpm_modules
    cpm_modules:
      short: cpm_modules
      long: Save modules in cpm_modules
      settings:
        CPM_SOURCE_CACHE: cpm_modules

useLocalPackages:
  default: uselocal 
  choices:
    onlylocal:
      short: Onlylocal
      long: Use only local packages. (not recommended)
      settings:
        CPM_LOCAL_PACKAGES_ONLY: ON
        CPM_USE_LOCAL_PACKAGES: OFF
        CPM_DOWNLOAD_ALL: OFF
    uselocal:
      short: UseLocal
      long: Use local packages, if they exist on system, and if not, download them.
      settings:
        CPM_LOCAL_PACKAGES_ONLY: OFF
        CPM_USE_LOCAL_PACKAGES: ON
        CPM_DOWNLOAD_ALL: OFF
    downloadall:
      short: downloadAll
      long: Download all packages, no use of local packages ( except some CPMFindPackage stuff ).
      settings:
        CPM_LOCAL_PACKAGES_ONLY: OFF
        CPM_USE_LOCAL_PACKAGES: OFF
        CPM_DOWNLOAD_ALL: ON
```

I guess, this can be used at [ModernCppStarter](https://github.com/yunshouhu/ModernCppStarter)  to reproduce

**Expected behavior**

1. no cursed names of folders. replace " + " with "_" or something like. remove parentheses with details.  ( at least )
if not replace " + ", then change somehow command for cd : `cd ./cmake_build_UseLocal\ +\ Debug\ +\ cpm_modules\(Use\ local\ packages,\ if\ they\ exist\ on\ sy...\)/` or something like.
2. support for yaml comments ( maybe? )
3. support for names of options inside of " " .  (at least document that this is not supported ) 

**Environment**

- OS: Gentoo
- Desktop environment: KDE
- Plugins commits: a previous and last one  (  5697db80fb9a49f638d8bde3317f06e6e4faccfd ) are tested

**Comment by Civitasv** [comment]
Now, yaml support is weak. Can you translate it to json and test if it works?

**Comment by Civitasv** [comment]
The latest commit should fix this error. :smile:

**Comment by Civitasv** [comment]
> * support for yaml comments ( maybe? )
> * support for names of options inside of " " .  (at least document that this is not supported )

And currently yaml support is weak, maybe you can use json format, it's way more mature.

**Comment by Gerodote** [comment]
> The latest commit should fix this error. smile

Yep, this works.

:heavy_check_mark:  No cursed names 
:heavy_check_mark:  yaml comments are working !
:no_entry: no support  for "option" ( inside quotation marks ) 

Maybe last one put in documentation or place somewhere TODO about.

**Comment by Civitasv** [comment]
Okay. I will add it soon.
