### ISSUE TITLE
Encoding issues and compilation type detection

### ISSUE THREAD

**Issue by taynpg** [Civitasv/cmake-tools.nvim#88]
1. The first question, when I am in a Chinese environment, it will not be able to display Chinese, is there any way to deal with this?
![image](https://github.com/Civitasv/cmake-tools.nvim/assets/59216127/4e2b7e69-84a7-4289-b3a9-a3b35cf0f012)

2. When there are multiple compilers on my PC, such as the MSVC compiler and MinGW exist at the same time, I specify the MinGW compiler, but it cannot recognize it (MinGW has added environment variables and can be specified directly using the console)
![image](https://github.com/Civitasv/cmake-tools.nvim/assets/59216127/00c6ef58-14c1-425b-b380-d39b4f1debd1)

Execute directly using cmd:
![image](https://github.com/Civitasv/cmake-tools.nvim/assets/59216127/81126a97-3cc3-45f0-be19-e0285084eb03)

**Comment by Civitasv** [comment]
Can you show your configuration for cmake-tools.nvim?

**Comment by taynpg** [comment]
I use AstroNvim, and cmake-tools is added as a plug-in, but the configurations I add are all default, only cmake_build_directory is modified:

return {

  "AstroNvim/astrocommunity",
  { import = "astrocommunity.pack.cpp" },
  {
    "Civitasv/cmake-tools.nvim",
    opts = {
	    -- auto generate when save CMakeLists.txt
	    cmake_regenerate_on_save = true,
	    -- this will be passed when invoke `CMakeGenerate`
	    cmake_generate_options = { "-DCMAKE_EXPORT_COMPILE_COMMANDS=1" },
	    -- this will be passed when invoke `CMakeBuild`
	    cmake_build_options = {},
	    -- this is used to specify generate directory for cmake
	    cmake_build_directory = "build",
	    -- when cmake_build_directory is set to "", this option will be activated
	    cmake_build_directory_prefix = "cmake_build_",
	    -- this will automatically make a soft link from compile commands file to project root dir
	    cmake_soft_link_compile_commands = true,
	    -- this will automatically set compile commands file location using lsp, to use it,
	    -- please set `cmake_soft_link_compile_commands` to false
	    cmake_compile_commands_from_lsp = false,
	    cmake_kits_path = nil,
	    -- this is used to specify global cmake kits path, see CMakeKits for detailed usage
	    cmake_variants_message = {
		    -- whether to show short message
		    short = { show = true },
		    -- whether to show long message
		    long = { show = true, max_length = 40 },
	    },
	    -- debug settings for cmake
	    cmake_dap_configuration = {
		    name = "cpp",
		    type = "codelldb",
		    request = "launch",
		    stopOnEntry = false,
		    runInTerminal = true,
		    console = "integratedTerminal",
	    },
	    -- if true, use terminal for generate, build, clean, install, run, etc, except for debug,
	    -- else only use terminal for run, use quickfix for others
	    cmake_always_use_terminal = false,
	    -- quickfix settings for cmake, quickfix will be used when `cmake_always_use_terminal` is false
	    cmake_quickfix_opts = {
		    -- "always", "only_on_error"
		    show = "always",
		    -- "bottom", "top"
		    position = "belowright",
		    size = 10,
	    },
	    -- terminal settings for cmake, terminal will be used for run when `cmake_always_use_terminal` is false or true,
	    -- will be used for all tasks except for debug when `cmake_always_use_terminal` is true
	    cmake_terminal_opts = {
		    name = "Main Terminal",
		    -- This must be included and must be unique, otherwise the terminals will not work. Do not use a simple spacebar " ", or any generic name
		    prefix_name = "[CMakeTools]: ",
		    -- "horizontal", "vertical"
		    split_direction = "horizontal",
		    split_size = 11,

		    -- Window handling
		    single_terminal_per_instance = true, -- Single viewport, multiple windows
		    single_terminal_per_tab = true, -- Single viewport per tab
		    keep_terminal_static_location = true, -- Static location of the viewport if avialable

		    -- Running Tasks
		    -- If you want to enter terminal with :startinsert upon using :CMakeRun
		    start_insert_in_launch_task = false,
		    -- If you want to enter terminal with :startinsert upon launching all other cmake tasks in the terminal. Generally set as false
		    start_insert_in_other_tasks = false,
		    -- Focus on cmake terminal when cmake task is launched. Only used if cmake_always_use_terminal is true.
		    focus_on_main_terminal = false,
		    -- Focus on cmake launch terminal when executable target in launched.
		    focus_on_launch_terminal = false,
	    },
    },
  },
}

**Comment by Civitasv** [comment]
Maybe you can make `cmake_command` option point to your `MinGW cmake` location.

**Comment by Civitasv** [comment]
> 1. The first question, when I am in a Chinese environment, it will not be able to display Chinese, is there any way to deal with this?

Please print your current encoding use `chcp`.

**Comment by taynpg** [comment]
The garbled character problem is indeed an encoding problem, thank you, but what does "MinGW Cmake" mean, can you give an example?

**Comment by Civitasv** [comment]
I mean, you can change the option `cmake_command` of cmake-tools.nvim to the location of your cmake command, in this case, the cmake command path of MinGW.

**Comment by taynpg** [comment]
I didn't succeed, but it doesn't affect the use for the time being, because I mainly use the VC compiler, thank you for your help, you can close this bug report.
