### ISSUE TITLE
Configure cmake command to automatically run in a docker container 

### ISSUE THREAD

**Issue by patrickTumulty** [Civitasv/cmake-tools.nvim#91]
CLion has a nice feature that allows you to configure cmake to automatically run in a docker container. In my work, I am developing on a mac, but am working on C/C++ code that needs to be build and deployed in a linux environment. The nice thing about CLion is that when I define the docker container to run, everything else is abstracted away. I can simply build the project without having to think about starting up a container. 

Ideally I would like to be able to setup a docker image that cmake-tools can use to run all cmake commands in. That way code intelligence and built binaries would be created within the docker environment, not my laptop. 

I tried doing this to simply change the command used to call cmake under the hood, but this doesn't seem to work. 

```lau
require("cmake-tools").setup {
    cmake_command = "bash -c docker run --rm -v $(pwd):/home/dev-repo -w /home/dev-repo ubuntu20-container cmake"
}
```

I also realize I could probably setup neovim to run in the docker container and develop from there. 

Is there a way to achieve this behavior with the plugin as is? or would this need to be a new feature?

**Comment by Civitasv** [comment]
`cmake-tools.nvim` should run inside neovim. I think you can firstly enter into neovim instance of the dev container, then invoke commands of cmake-tools, that should be feasible.

**Comment by patrickTumulty** [comment]
As I've been looking more into this, I think I see a few ways that this could be achieved. Probably doesn't make sense to build this into cmake tools. 

Thanks for responding
