### ISSUE TITLE
cmake variants: default option support

### ISSUE THREAD

**Issue by Gerodote** [Civitasv/cmake-tools.nvim#95]
Right now if use cmake-variants, you still is requested to choose among a lot of options, but there's no default option, though in cmake-variants we write it. 

A possible solution: add the default option to the list from :CMakeSelectBuildType to position 1

Alternative solution: if entered no number, choose default.

Possible problems:  checking if there's default for every choice.

**Comment by Civitasv** [comment]
Actually, you only need to select once, we support session save and load.

**Comment by Gerodote** [comment]
> Actually, you only need to select once, we support session save and load.

You are right about the capability. 
Though, I'm about simplifying even further: if someone have to select something, he can press 1 or nothing to set default option. It will make redundant for developers to find that specific option among hundreds and thousands of options, if they just want default proposed by cmake-variants.* .

**Comment by Civitasv** [comment]
I've enabled default option, use the latest commit.
