### ISSUE TITLE
Call cmake.build() with callback will not build

### ISSUE THREAD

**Issue by AbaoFromCUG** [Civitasv/cmake-tools.nvim#99]
**Bug description**

https://github.com/Civitasv/cmake-tools.nvim/blob/213932932d1fb17d513a40343ce9f7f026197847/lua/cmake-tools/init.lua#L108-L118

As the code show,  when `config.cmake_always_use_terminal` is true, I call `cmake.build(opt, callback)`  with a callback function, the callbak will be called immediately without build

**Steps to reproduce**

<details><summary>Minimal configuration</summary>

```lua
    require 'cmake-tools'.setup {
        cmake_build_directory = 'build',
        cmake_always_use_terminal = true,
        cmake_soft_link_compile_commands = false,
    }

```

</details>

add keymap to cmake.build with callback, such as 
```lua
function()
    require 'cmake-tools'.build({ bang = false }, function()
          vim.notify("Cmake build success")
    end)
end
```

**Expected behavior**

Build success, then call callabck

**Environment**

- OS: ArchLinux
- NVIM v0.9.1
- Plugins commit hash: 2139329

**Another proposal**

Another proposal, expose local variable `config` in  `cmake-tools/init.lua` for conveniently obtaining information, e.g. target_binary_path

**Comment by Civitasv** [comment]
Yes, when `cmake_always_use_terminal` is true, and callback is not nil, it will be invoked at once, also the command cannot be transfered to terminal. As we cannot find a proper way to register callback for terminal (See discussions: #60, PR is welcome).

So, for now, if you want to use callback, you should set `cmake_always_use_terminal` to false and use quickfix mode.

**Comment by AbaoFromCUG** [comment]
Yeah, terminal is a complex component, can we use [toggleterm](https://github.com/akinsho/toggleterm.nvim#custom-terminals) directly?

In another neovim plugin named [overseer.nvim](https://github.com/stevearc/overseer.nvim/blob/master/doc/strategies.md#toggletermopts), which supoort different run method, include:
* builtin terminal: using `termopen()`
* jobstart()
* toggleterm(): integrate with `ToggleTerm`

**Comment by Civitasv** [comment]
Yeah, I will consider it.
